# Copyright 2026 wrx-jp contributors
#
# This driver is adapted from the Quansheng UV-K5 CHIRP driver published by
# armel/uv-k5-chirp-driver.  See LICENSE.txt and NOTICE.md for attribution.
# The armel repository is distributed under CC BY-SA 4.0.
#
# wrx-jp is an RX-only Japanese firmware.  This driver deliberately does not
# expose transmit frequency, transmit tone, PTT, or power controls.

"""CHIRP driver for the UV-K1 / UV-K5 V3 wrx-jp RX-only firmware."""

import base64
import binascii
import json
import logging
from pathlib import Path
import struct
import zlib

from chirp import chirp_common, directory, errors, memmap
from chirp.settings import (
    InvalidValueError,
    RadioSetting,
    RadioSettingGroup,
    RadioSettings,
    RadioSettingValueBoolean,
    RadioSettingValueInteger,
    RadioSettingValueList,
    RadioSettingValueString,
)


LOG = logging.getLogger(__name__)

MEM_BLOCK = 0x80
EXTERNAL_BLOCK = 0x80
EXTERNAL_WRITE_RETRIES = 3
EXTERNAL_SESSION_TIMESTAMP = 0x6457396A
JAPANESE_NAME_RECORD_SIZE = 32
JAPANESE_NAME_PAYLOAD_MAX = 31
# CHIRP exposes a character-count limit, while the wire contract is in bytes
# and LCD pixels.  Ten also preserves the existing ASCII slot's usable length;
# the write-time checks apply the stricter limit for each mixed name.
JAPANESE_NAME_CHARACTER_MAX = 10
JAPANESE_NAME_TABLE_SIZE = 1024 * JAPANESE_NAME_RECORD_SIZE
FM_MIN = 760  # 76.0 MHz, stored in 0.1 MHz units
FM_MAX = 950  # 95.0 MHz, Japanese FM broadcast limit

CHANNEL_DISPLAY_LIST = (
    "周波数", "チャンネル番号", "名前", "名前＋周波数",
)
BATTERY_SAVE_LIST = ("OFF", "1:1", "1:2", "1:3", "1:4", "1:5")
DUAL_WATCH_LIST = ("OFF", "A", "B")
POWER_ON_DISPLAY_LIST = (
    "全画面", "音声", "メッセージ", "電圧", "ロゴ", "ロゴ＋メッセージ",
    "ロゴ＋全画面", "なし",
)
BATTERY_TYPE_LIST = (
    "1600mAh K5", "2200mAh K5", "3500mAh K5", "1500mAh K1", "2500mAh K1",
)
FM_AUDIO_LIST = ("FLAT", "CLEAN", "MID", "BOOST", "MAX")
AM_AUDIO_LIST = ("SHARP", "STOCK", "OPEN")
MENU_LOCK_LIST = ("キー", "キー＋操作", "キー＋PTT", "キー＋操作＋PTT")
METER_LIST = ("TINY", "CLASSIC")
SCAN_LIST_CHOICES = tuple(
    ["リスト %d" % index for index in range(1, 25)] + ["全チャンネル"])


def _make_backlight_list():
    values = ["OFF"]
    for seconds in range(5, 301, 5):
        if seconds < 60:
            values.append("%d秒" % seconds)
        elif seconds % 60 == 0:
            values.append("%d分" % (seconds // 60))
        else:
            values.append("%d分%02d秒" % (seconds // 60, seconds % 60))
    values.append("常時点灯")
    return tuple(values)


def _make_auto_keypad_lock_list():
    values = ["OFF"]
    for seconds in range(15, 601, 15):
        values.append("%d分%02d秒" % (seconds // 60, seconds % 60))
    return tuple(values)


def _make_sleep_timer_list():
    return tuple(["OFF"] + ["%d分" % minutes for minutes in range(1, 121)])


def _make_scan_resume_list():
    values = ["停止"]
    values.extend("キャリア解消後 %.2f秒" % (value * 0.25)
                  for value in range(1, 81))
    values.extend("タイムアウト後 %d秒" % ((value - 80) * 5)
                  for value in range(81, 105))
    return tuple(values)


BACKLIGHT_LIST = _make_backlight_list()
AUTO_KEYPAD_LOCK_LIST = _make_auto_keypad_lock_list()
SLEEP_TIMER_LIST = _make_sleep_timer_list()
SCAN_RESUME_LIST = _make_scan_resume_list()

# ACTION_OPT_t in the RX-only build ends at ACTION_OPT_RXA (20).  Keep the
# numeric order identical to settings.h so existing assignments survive a
# download/upload round trip.  Entries blocked or compiled as no-ops are
# labelled explicitly instead of exposing transmit controls as usable ones.
ACTION_LIST = (
    "なし", "ライト", "電源（RX-only無効）", "モニター", "スキャン",
    "VOX（無効）", "アラーム（無効）", "FMラジオ", "1750Hz（RX-only無効）",
    "キーロック", "A/B切替", "VFO/メモリ切替", "モード切替", "最低輝度解除",
    "受信モード", "受信専用", "PTT（RX-only無効）", "W/N",
    "バックライト", "ミュート", "受信音声",
)


_DRIVER_DIR = Path(__file__).resolve().parent
_REPOSITORY_ROOT = Path(__file__).resolve().parents[2]

# The development module reads these files from the repository.  The release
# module generated by tools/build_chirp_module.py replaces this block with
# compressed, embedded copies so CHIRP can load one .py file by itself.
# BEGIN GENERATED EMBEDDED FONT BLOCK
_EMBEDDED_FONT_MANIFEST_ZLIB_BASE64 = None
_EMBEDDED_FONT_BINARY_ZLIB_BASE64 = None
# END GENERATED EMBEDDED FONT BLOCK


def _resource_path(name, repository_relative):
    bundled = _DRIVER_DIR / name
    return bundled if bundled.is_file() else _REPOSITORY_ROOT / repository_relative


JAPANESE_FONT_MANIFEST_PATH = _resource_path(
    "japanese_font_manifest.json", Path("tools") / "japanese_font_manifest.json")
JAPANESE_FONT_BINARY_PATH = _resource_path(
    "japanese_font.bin", Path("docs") / "fonts" / "japanese_font.bin")


def _load_japanese_font_manifest():
    if _EMBEDDED_FONT_MANIFEST_ZLIB_BASE64:
        try:
            encoded = base64.b64decode(_EMBEDDED_FONT_MANIFEST_ZLIB_BASE64)
            return json.loads(zlib.decompress(encoded).decode("utf-8"))
        except (binascii.Error, UnicodeDecodeError, ValueError, zlib.error):
            LOG.warning("Embedded Japanese font manifest is invalid")
    try:
        with JAPANESE_FONT_MANIFEST_PATH.open("r", encoding="utf-8") as source:
            return json.load(source)
    except (OSError, ValueError):
        return {
            "flash_base": 0x020000,
            "total_bytes": 0,
            "name_table_base": 0x040000,
            "codepoints": [],
        }


def _load_japanese_font_data():
    if _EMBEDDED_FONT_BINARY_ZLIB_BASE64:
        try:
            encoded = base64.b64decode(_EMBEDDED_FONT_BINARY_ZLIB_BASE64)
            return zlib.decompress(encoded)
        except (binascii.Error, zlib.error) as exc:
            raise errors.RadioError("Embedded Japanese font is corrupt") from exc
    try:
        return JAPANESE_FONT_BINARY_PATH.read_bytes()
    except OSError as exc:
        raise errors.RadioError(
            "Japanese font binary is missing: {}".format(
                JAPANESE_FONT_BINARY_PATH)) from exc


_JAPANESE_FONT_MANIFEST = _load_japanese_font_manifest()
JAPANESE_FONT_BASE = int(_JAPANESE_FONT_MANIFEST["flash_base"])
JAPANESE_FONT_SIZE = int(_JAPANESE_FONT_MANIFEST["total_bytes"])
JAPANESE_NAME_BASE = int(_JAPANESE_FONT_MANIFEST["name_table_base"])
JAPANESE_CODEPOINTS = frozenset(
    int(codepoint) for codepoint in _JAPANESE_FONT_MANIFEST.get("codepoints", [])
)

BANDS_WIDE = (
    (18.0, 108.0),
    (108.0, 136.9999),
    (137.0, 173.9999),
    (174.0, 349.9999),
    (350.0, 399.9999),
    (400.0, 469.9999),
    (470.0, 1300.0),
)

STEPS = (
    2.5, 5, 6.25, 10, 12.5, 25, 8.33, 0.01, 0.05, 0.1, 0.25, 0.5,
    1, 1.25, 9, 15, 20, 30, 50, 100, 125, 200, 250, 500,
)

CTCSS_TONES = (
    67.0, 69.3, 71.9, 74.4, 77.0, 79.7, 82.5, 85.4, 88.5, 91.5,
    94.8, 97.4, 100.0, 103.5, 107.2, 110.9, 114.8, 118.8, 123.0,
    127.3, 131.8, 136.5, 141.3, 146.2, 151.4, 156.7, 159.8, 162.2,
    165.5, 167.9, 171.3, 173.8, 177.3, 179.9, 183.5, 186.2, 189.9,
    192.8, 196.6, 199.5, 203.5, 206.5, 210.7, 218.1, 225.7, 229.1,
    233.6, 241.8, 250.3, 254.1,
)

DTCS_CODES = (
    23, 25, 26, 31, 32, 36, 43, 47, 51, 53, 54, 65, 71, 72, 73, 74,
    114, 115, 116, 122, 125, 131, 132, 134, 143, 145, 152, 155, 156,
    162, 165, 172, 174, 205, 212, 223, 225, 226, 243, 244, 245, 246,
    251, 252, 255, 261, 263, 265, 266, 271, 274, 306, 311, 315, 325,
    331, 332, 343, 346, 351, 356, 364, 365, 371, 411, 412, 413, 423,
    431, 432, 445, 446, 452, 454, 455, 462, 464, 465, 466, 503, 506,
    516, 523, 526, 532, 546, 565, 606, 612, 624, 627, 631, 632, 654,
    662, 664, 703, 712, 723, 731, 732, 734, 743, 754,
)


class _Profile:
    def __init__(self, name, image_size, memory_channels, special_base,
                 name_base, attr_base, attr_width, attr_limit, fm_cfg,
                 fm_channels, fm_count, upload_ranges, settings_base,
                 action_settings_base, scan_settings_base, f4hwn_base,
                 logo_base):
        self.name = name
        self.image_size = image_size
        self.memory_channels = memory_channels
        self.special_base = special_base
        self.name_base = name_base
        self.attr_base = attr_base
        self.attr_width = attr_width
        self.attr_limit = attr_limit
        self.fm_cfg = fm_cfg
        self.fm_channels = fm_channels
        self.fm_count = fm_count
        self.upload_ranges = upload_ranges
        self.settings_base = settings_base
        self.action_settings_base = action_settings_base
        self.scan_settings_base = scan_settings_base
        self.f4hwn_base = f4hwn_base
        self.logo_base = logo_base

    @property
    def special_count(self):
        return len(BANDS_WIDE) * 2

    @property
    def attr_scanlist_max(self):
        return 0xFF if self.attr_width == 2 else 0x07


# K1 and K5 V3 use the same map.  The 0xB000-0xB1FF area is a mapped
# calibration backup; the RX feature state is at a different physical flash
# address and is intentionally not exposed through this clone driver.
PY32_PROFILE = _Profile(
    "PY32F071 / external flash",
    0xB200,
    1024,
    0x9000,
    0x4000,
    0x8000,
    2,
    1031,
    0xA020,
    0xA028,
    48,
    ((0x0000, 0x886E), (0x9000, 0x90E7), (0xA000, 0xA170)),
    0xA000,
    0xA0A8,
    0xA130,
    0xA158,
    0xA0C8,
)

def xorarr(data):
    table = (22, 108, 20, 230, 46, 145, 13, 64, 33, 53, 213, 64,
             19, 3, 233, 128)
    return bytes(byte ^ table[index % len(table)]
                 for index, byte in enumerate(data))


def _crc16_xmodem(data):
    crc = 0
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc <<= 1
            if crc & 0x10000:
                crc = (crc ^ 0x1021) & 0xFFFF
    return crc & 0xFFFF


def _send_command(serport, data):
    packet = data + struct.pack("<H", _crc16_xmodem(data))
    command = struct.pack(">HBB", 0xABCD, len(data), 0)
    command += xorarr(packet) + struct.pack(">H", 0xDCBA)
    try:
        return serport.write(command)
    except Exception as exc:
        raise errors.RadioError("Error writing data to radio") from exc


def _receive_reply(serport):
    header = serport.read(4)
    if len(header) != 4 or header[:2] != b"\xAB\xCD" or header[3] != 0:
        raise errors.RadioError("Bad response header")
    body = serport.read(header[2])
    if len(body) != header[2]:
        raise errors.RadioError("Command body short read")
    footer = serport.read(4)
    if len(footer) != 4 or footer[2:] != b"\xDC\xBA":
        raise errors.RadioError("Bad response footer")
    return xorarr(body)


def _get_string(data, begin, maxlen):
    result = []
    for byte in data[begin:begin + maxlen]:
        if byte < 0x20 or byte > 0x7E:
            break
        result.append(chr(byte))
    return "".join(result)


def _say_hello(serport):
    hello = b"\x14\x05\x04\x00\x6a\x39\x57\x64"
    for _ in range(5):
        _send_command(serport, hello)
        reply = _receive_reply(serport)
        if reply:
            if reply.startswith(b"\x18\x05"):
                raise errors.RadioError("Radio is in programming mode")
            return _get_string(reply, 4, 24)
    raise errors.RadioError("Failed to initialize radio")


def _read_memory(serport, offset, length):
    command = b"\x1b\x05\x08\x00"
    command += struct.pack("<HBB", offset, length, 0)
    command += b"\x6a\x39\x57\x64"
    _send_command(serport, command)
    reply = _receive_reply(serport)
    data = reply[8:]
    if len(data) != length:
        raise errors.RadioError("Memory read length mismatch")
    return data


def _write_memory(serport, offset, data):
    if len(data) == 0 or len(data) % 8:
        raise errors.RadioError("Memory writes must be a multiple of 8 bytes")
    command = b"\x1d\x05"
    command += struct.pack("<BBHBB", len(data) + 8, 0, offset,
                           len(data), 1)
    command += b"\x6a\x39\x57\x64" + data
    _send_command(serport, command)
    reply = _receive_reply(serport)
    if len(reply) < 6 or reply[0] != 0x1E or reply[4:6] != struct.pack(
            "<H", offset):
        raise errors.RadioError("Bad response to memory write")


def _read_external(serport, address, length):
    if length <= 0:
        return b""
    result = bytearray()
    offset = 0
    while offset < length:
        block_length = min(EXTERNAL_BLOCK, length - offset)
        command = struct.pack(
            "<HHIB3xI", 0x0531, 12, address + offset, block_length,
            EXTERNAL_SESSION_TIMESTAMP)
        _send_command(serport, command)
        reply = _receive_reply(serport)
        if (len(reply) < 12 + block_length or
                struct.unpack_from("<H", reply, 0)[0] != 0x0532 or
                struct.unpack_from("<I", reply, 4)[0] != address + offset or
                reply[8] != block_length):
            raise errors.RadioError("Bad response to external flash read")
        result.extend(reply[12:12 + block_length])
        offset += block_length
    return bytes(result)


def _write_external_once(serport, address, data):
    if len(data) == 0 or len(data) > EXTERNAL_BLOCK:
        raise errors.RadioError("External flash writes must be 1..128 bytes")
    command = struct.pack(
        "<HHIBBHI", 0x0533, 12 + len(data), address, len(data), 1, 0,
        EXTERNAL_SESSION_TIMESTAMP) + data
    _send_command(serport, command)
    reply = _receive_reply(serport)
    if (len(reply) < 12 or
            struct.unpack_from("<H", reply, 0)[0] != 0x0534 or
            struct.unpack_from("<I", reply, 4)[0] != address or
            reply[8] != len(data) or reply[9] != 0):
        raise errors.RadioError("External flash write rejected")


def _write_external_verified(serport, address, data):
    for offset in range(0, len(data), EXTERNAL_BLOCK):
        block = data[offset:offset + EXTERNAL_BLOCK]
        last_error = None
        for _attempt in range(EXTERNAL_WRITE_RETRIES):
            try:
                _write_external_once(serport, address + offset, block)
                if _read_external(
                        serport, address + offset, len(block)) == block:
                    break
            except errors.RadioError as exc:
                last_error = exc
        else:
            message = "External flash readback failed at 0x{:06X}".format(
                address + offset)
            if last_error is not None:
                raise errors.RadioError(message) from last_error
            raise errors.RadioError(message)


def _ensure_external_font(serport):
    if JAPANESE_FONT_SIZE <= 0:
        raise errors.RadioError("Japanese font manifest is missing")
    font_data = _load_japanese_font_data()
    if len(font_data) != JAPANESE_FONT_SIZE:
        raise errors.RadioError("Japanese font binary size does not match the manifest")
    try:
        current = _read_external(serport, JAPANESE_FONT_BASE, len(font_data))
    except errors.RadioError as exc:
        raise errors.RadioError(
            "Japanese font transfer requires the JpRxOnly firmware with "
            "external-flash support") from exc
    if current != font_data:
        _write_external_verified(serport, JAPANESE_FONT_BASE, font_data)


def _decode_name_record(record):
    payload = bytes(record).split(b"\x00", 1)[0].split(b"\xFF", 1)[0]
    if not payload:
        return ""
    try:
        return payload.decode("utf-8")
    except UnicodeDecodeError:
        return ""


def _validate_japanese_name(name):
    try:
        encoded_name = name.encode("utf-8")
    except UnicodeEncodeError as exc:
        raise errors.RadioError("Channel name is not valid UTF-8") from exc

    if len(encoded_name) > JAPANESE_NAME_PAYLOAD_MAX:
        raise errors.RadioError("Channel name exceeds 31 UTF-8 bytes")

    pixel_width = 0
    for character in name:
        codepoint = ord(character)
        if codepoint < 0x20 or codepoint > 0x7E:
            if codepoint not in JAPANESE_CODEPOINTS:
                raise errors.RadioError(
                    "Channel name character U+{:04X} is not in the Japanese font".format(codepoint))
            pixel_width += 16
        else:
            pixel_width += 8
    if pixel_width > 95:
        raise errors.RadioError("Channel name exceeds the LCD display width")
    return encoded_name


def _reset_radio(serport):
    _send_command(serport, b"\xDD\x05\x00\x00")


def _download(radio):
    serport = radio.pipe
    serport.timeout = 0.5
    status = chirp_common.Status()
    status.cur = 0
    status.max = radio.PROFILE.image_size
    status.msg = "Downloading RX-only image"
    radio.status_fn(status)
    firmware = _say_hello(serport)
    if firmware:
        radio.FIRMWARE_VERSION = firmware

    image = bytearray(radio.PROFILE.image_size)
    for offset in range(0, radio.PROFILE.image_size, MEM_BLOCK):
        data = _read_memory(serport, offset, min(
            MEM_BLOCK, radio.PROFILE.image_size - offset))
        image[offset:offset + len(data)] = data
        status.cur = offset + len(data)
        radio.status_fn(status)
    return memmap.MemoryMapBytes(bytes(image))


def _rounded_upload_end(end):
    return (end + 7) & ~7


def _upload(radio):
    serport = radio.pipe
    serport.timeout = 0.5
    status = chirp_common.Status()
    status.cur = 0
    status.max = sum(_rounded_upload_end(end) - start
                     for start, end in radio.PROFILE.upload_ranges)
    status.msg = "Uploading RX-only image"
    radio.status_fn(status)
    firmware = _say_hello(serport)
    if firmware:
        radio.FIRMWARE_VERSION = firmware

    if radio._supports_external_japanese():
        status.msg = "Checking Japanese font support"
        radio.status_fn(status)
        # Probe the custom external-flash command before changing the normal
        # memory image.  Stock firmware must fail here without a partial upload.
        _ensure_external_font(serport)

    done = 0
    for start, end in radio.PROFILE.upload_ranges:
        offset = start
        limit = _rounded_upload_end(end)
        while offset < limit:
            length = min(MEM_BLOCK, limit - offset)
            if length % 8:
                length -= length % 8
            data = bytes(radio.get_mmap()[offset:offset + length])
            _write_memory(serport, offset, data)
            offset += length
            done += length
            status.cur = done
            radio.status_fn(status)
    if radio._supports_external_japanese():
        if radio._japanese_names_dirty:
            status.msg = "Uploading Japanese channel names"
            radio.status_fn(status)
            _write_external_verified(
                serport, JAPANESE_NAME_BASE, radio._japanese_names)
            radio._japanese_names_dirty = False
    status.msg = "Uploaded RX-only image"
    radio.status_fn(status)
    _reset_radio(serport)


def _u16(data, offset):
    return struct.unpack_from("<H", data, offset)[0]


def _put_u16(data, offset, value):
    struct.pack_into("<H", data, offset, value & 0xFFFF)


class _WRXJPBase(chirp_common.CloneModeRadio):
    BAUD_RATE = 38400
    NEEDS_COMPAT_SERIAL = False
    FIRMWARE_VERSION = ""
    PROFILE = None

    def __init__(self, pipe=None):
        super().__init__(pipe)
        self._japanese_names = bytearray(JAPANESE_NAME_TABLE_SIZE)
        self._japanese_names_dirty = False

    def _supports_external_japanese(self):
        return True

    def _external_name_offset(self, index):
        return index * JAPANESE_NAME_RECORD_SIZE

    def _clear_external_name(self, index):
        if not self._supports_external_japanese():
            return
        offset = self._external_name_offset(index)
        self._japanese_names[offset:offset + JAPANESE_NAME_RECORD_SIZE] = \
            b"\x00" * JAPANESE_NAME_RECORD_SIZE
        self._japanese_names_dirty = True

    def _set_external_name(self, index, encoded):
        offset = self._external_name_offset(index)
        self._japanese_names[offset:offset + JAPANESE_NAME_RECORD_SIZE] = \
            encoded.ljust(JAPANESE_NAME_RECORD_SIZE, b"\x00")
        self._japanese_names_dirty = True

    @classmethod
    def get_prompts(cls):
        prompts = chirp_common.RadioPrompts()
        prompts.experimental = (
            "wrx-jp RX-only driver. Keep a complete download as backup before "
            "uploading. This driver never enables transmission."
        )
        prompts.pre_download = (
            "Turn the radio on, connect the programming cable, and keep the "
            "cable firmly inserted. Download and save the image first."
        )
        prompts.pre_upload = (
            "First install the JpRxOnly firmware for this hardware. Then "
            "upload only an image made for this exact profile; the Japanese "
            "font uses the firmware's external-flash command."
        )
        return prompts

    def _special_names(self):
        result = []
        for index, (low, high) in enumerate(BANDS_WIDE):
            label = "F%d(%g-%gM)" % (index + 1, low, high)
            result.extend((label + "A", label + "B"))
        return result

    def _find_band(self, frequency):
        mhz = frequency / 1000000.0
        for index, (low, high) in enumerate(BANDS_WIDE):
            if low <= mhz <= high:
                return index
        return None

    def _resolve_memory(self, number):
        if isinstance(number, str):
            try:
                return True, self._special_names().index(number)
            except ValueError as exc:
                raise errors.RadioError("Unknown special channel") from exc
        if number < 1 or number > self.PROFILE.memory_channels + self.PROFILE.special_count:
            raise errors.RadioError("Channel number out of range")
        if number <= self.PROFILE.memory_channels:
            return False, number - 1
        return True, number - self.PROFILE.memory_channels - 1

    def _channel_offset(self, special, index):
        if special:
            return self.PROFILE.special_base + index * 16
        return index * 16

    def _attribute_offset(self, special, index):
        attr_index = (self.PROFILE.memory_channels + index // 2
                      if special else index)
        if attr_index >= self.PROFILE.attr_limit:
            raise errors.RadioError("Channel attribute out of range")
        return self.PROFILE.attr_base + attr_index * self.PROFILE.attr_width

    def _name_offset(self, index):
        return self.PROFILE.name_base + index * 16

    def _get_scanlists(self, special, index):
        offset = self._attribute_offset(special, index)
        raw = bytes(self._mmap[offset:offset + self.PROFILE.attr_width])
        if self.PROFILE.attr_width == 2:
            return _u16(raw, 0) >> 8
        return raw[0] >> 5

    def _set_scanlists(self, special, index, value):
        offset = self._attribute_offset(special, index)
        raw = bytearray(self._mmap[offset:offset + self.PROFILE.attr_width])
        value = max(0, min(self.PROFILE.attr_scanlist_max, int(value)))
        if self.PROFILE.attr_width == 2:
            _put_u16(raw, 0, (int.from_bytes(raw, "little") & 0x00FF) |
                     (value << 8))
        else:
            raw[0] = (raw[0] & 0x1F) | (value << 5)
        self._set_mmap_bytes(offset, raw)

    def _set_band(self, special, index, band):
        offset = self._attribute_offset(special, index)
        raw = bytearray(self._mmap[offset:offset + self.PROFILE.attr_width])
        if self.PROFILE.attr_width == 2:
            value = int.from_bytes(raw, "little")
            _put_u16(raw, 0, (value & ~0x07) | (band & 0x07))
        else:
            raw[0] = (raw[0] & ~0x07) | (band & 0x07)
        self._set_mmap_bytes(offset, raw)

    def _get_mmap_u16(self, offset):
        raw = bytes(self._mmap[offset:offset + 2])
        return _u16(raw, 0)

    def _set_mmap_u16(self, offset, value):
        raw = bytearray(self._mmap[offset:offset + 2])
        _put_u16(raw, 0, value)
        self._set_mmap_bytes(offset, raw)

    def _set_mmap_bytes(self, offset, data):
        data = bytes(data)
        setter = getattr(self._mmap, "set", None)
        if setter is not None:
            setter(offset, data)
        else:
            self._mmap[offset:offset + len(data)] = data

    @staticmethod
    def _choice_value(choices, value, default=0):
        try:
            index = int(value)
        except (TypeError, ValueError, InvalidValueError):
            index = default
        return choices[max(0, min(len(choices) - 1, index))]

    @staticmethod
    def _choice_index(value, choices, setting_name):
        text = str(value)
        try:
            return choices.index(text)
        except ValueError as exc:
            raise errors.RadioError(
                "Invalid value for %s: %s" % (setting_name, text)) from exc

    @staticmethod
    def _int_value(value, setting_name, minimum=None, maximum=None):
        try:
            result = int(value)
        except (TypeError, ValueError, InvalidValueError) as exc:
            raise errors.RadioError(
                "Invalid value for %s" % setting_name) from exc
        if minimum is not None and result < minimum:
            raise errors.RadioError("%s is below its minimum" % setting_name)
        if maximum is not None and result > maximum:
            raise errors.RadioError("%s is above its maximum" % setting_name)
        return result

    @staticmethod
    def _bool_value(value):
        try:
            return 1 if int(value) else 0
        except (TypeError, ValueError, InvalidValueError):
            return 1 if bool(value) else 0

    @staticmethod
    def _ascii_value(raw):
        result = []
        for byte in raw:
            if byte in (0x00, 0xFF):
                break
            if not 0x20 <= byte <= 0x7E:
                break
            result.append(chr(byte))
        return "".join(result)

    def _append_list_setting(self, group, name, label, choices, index,
                             default=0):
        group.append(RadioSetting(
            name, label,
            RadioSettingValueList(
                choices, self._choice_value(choices, index, default))))

    @staticmethod
    def _collect_settings(settings, values):
        for element in settings:
            if isinstance(element, RadioSetting):
                values[element.get_name()] = element.value
            else:
                _WRXJPBase._collect_settings(element, values)

    def _extra_group(self, special, index):
        extra = RadioSettingGroup("extra", "RX-only")
        current = self._get_scanlists(special, index)
        value = RadioSettingValueInteger(
            0, self.PROFILE.attr_scanlist_max, current)
        setting = RadioSetting("scanlists", "RX scan-list mask", value)
        setting.set_doc(
            "RX-only scan-list mask. K1/K5 V3 uses 8 bits.")
        extra.append(setting)
        return extra

    def _decode_tone(self, memory, raw):
        flag = raw[10] & 0x0F
        code = raw[8]
        if flag == 1 and code < len(CTCSS_TONES):
            rx = ("Tone", CTCSS_TONES[code], "N")
        elif flag in (2, 3) and code < len(DTCS_CODES):
            rx = ("DTCS", DTCS_CODES[code], "R" if flag == 3 else "N")
        else:
            rx = ("", None, "N")
        chirp_common.split_tone_decode(memory, ("", None, "N"), rx)

    def _encode_tone(self, memory, raw):
        flag = 0
        code = 0
        mode = getattr(memory, "tmode", "")
        if mode in ("Tone", "TSQL"):
            tone = getattr(memory, "ctone", None)
            if tone is None:
                tone = getattr(memory, "rtone", None)
            if tone in CTCSS_TONES:
                code = CTCSS_TONES.index(tone)
                flag = 1
        elif mode == "DTCS":
            tone = getattr(memory, "dtcs", None)
            if tone in DTCS_CODES:
                code = DTCS_CODES.index(tone)
                polarity = getattr(memory, "rx_dtcs_polarity", "N")
                flag = 3 if polarity == "R" else 2
        # Keep the upper nibble free of TX tone configuration.
        raw[8] = code
        raw[9] = 0
        raw[10] = (raw[10] & 0xF0) | flag

    def _get_mode(self, raw):
        mode_index = ((raw[11] >> 4) & 0x0F) * 2 + ((raw[12] >> 1) & 1)
        modes = ("FM", "NFM", "AM", "NAM", "USB", "USB")
        return modes[mode_index] if mode_index < len(modes) else "FM"

    def _set_mode(self, raw, mode):
        modes = {"FM": 0, "NFM": 1, "AM": 2, "NAM": 3, "USB": 5}
        mode_index = modes.get(mode, 0)
        raw[11] = (raw[11] & 0x0F) | ((mode_index // 2) << 4)
        raw[12] = (raw[12] & 0xFD) | ((mode_index & 1) << 1)

    def get_features(self):
        features = chirp_common.RadioFeatures()
        features.has_bank = False
        features.has_settings = True
        features.has_comment = False
        features.has_rx_dtcs = True
        features.has_ctone = True
        features.valid_name_length = JAPANESE_NAME_CHARACTER_MAX
        features.valid_special_chans = self._special_names()
        features.valid_bands = [
            (int(low * 1000000), int(high * 1000000))
            for low, high in BANDS_WIDE
        ]
        features.valid_duplexes = [""]
        features.valid_modes = ["FM", "NFM", "AM", "NAM", "USB"]
        features.valid_tuning_steps = sorted(STEPS)
        features.valid_tmodes = ["", "TSQL", "DTCS"]
        features.valid_cross_modes = []
        if self._supports_external_japanese():
            features.valid_characters = chirp_common.CHARSET_ASCII + "".join(
                chr(codepoint) for codepoint in sorted(JAPANESE_CODEPOINTS))
        else:
            features.valid_characters = chirp_common.CHARSET_ASCII
        features.valid_skips = [""]
        features.memory_bounds = (1, self.PROFILE.memory_channels)
        features.valid_power_levels = []
        return features

    def sync_in(self):
        self._mmap = _download(self)
        if self._supports_external_japanese():
            self._japanese_names[:] = _read_external(
                self.pipe, JAPANESE_NAME_BASE, JAPANESE_NAME_TABLE_SIZE)
            self._japanese_names_dirty = False

    def sync_out(self):
        _upload(self)

    def get_raw_memory(self, number):
        special, index = self._resolve_memory(number)
        offset = self._channel_offset(special, index)
        return repr(bytes(self._mmap[offset:offset + 16]))

    def get_memory(self, number):
        special, index = self._resolve_memory(number)
        memory = chirp_common.Memory()
        memory.number = (self.PROFILE.memory_channels + index + 1
                         if special else index + 1)
        if special:
            memory.extd_number = self._special_names()[index]
            memory.name = memory.extd_number
            memory.immutable = ["name", "scanlists"]
        else:
            external_name = ""
            if self._supports_external_japanese():
                offset = self._external_name_offset(index)
                external_name = _decode_name_record(
                    self._japanese_names[offset:offset + JAPANESE_NAME_RECORD_SIZE])
            if external_name:
                memory.name = external_name
            else:
                raw_name = bytes(self._mmap[self._name_offset(index):
                                            self._name_offset(index) + 16])
                memory.name = raw_name.split(b"\x00", 1)[0].split(
                    b"\xFF", 1)[0].decode("ascii", errors="ignore").rstrip()

        offset = self._channel_offset(special, index)
        raw = bytes(self._mmap[offset:offset + 16])
        frequency = struct.unpack_from("<I", raw, 0)[0]
        memory.offset = 0
        memory.duplex = ""
        memory.mode = self._get_mode(raw)
        memory.tuning_step = (STEPS[raw[14]] if raw[14] < len(STEPS)
                              else 12.5)
        self._decode_tone(memory, raw)
        memory.extra = self._extra_group(special, index)
        memory.empty = frequency in (0, 0xFFFFFFFF)
        memory.freq = 0 if memory.empty else frequency * 10
        if memory.empty:
            memory.name = "" if not special else memory.name
        return memory

    def _scanlist_value(self, memory, current):
        try:
            for setting in memory.extra:
                if setting.get_name() == "scanlists":
                    return int(setting.value)
        except (AttributeError, TypeError, ValueError):
            pass
        return current

    def set_memory(self, memory):
        special, index = self._resolve_memory(
            memory.extd_number if getattr(memory, "extd_number", None)
            else memory.number)
        offset = self._channel_offset(special, index)
        raw = bytearray(self._mmap[offset:offset + 16])
        if memory.empty:
            raw[:] = b"\xFF" * 16
            self._set_mmap_bytes(offset, raw)
            if not special:
                self._set_mmap_bytes(
                    self._name_offset(index), b"\x00" * 16)
                self._clear_external_name(index)
            return memory

        band = self._find_band(memory.freq)
        if band is None:
            raise errors.RadioError("Receive frequency is outside wrx-jp bands")
        struct.pack_into("<I", raw, 0, int(memory.freq // 10))
        # RX-only: never retain a duplex or a transmit tone.
        struct.pack_into("<I", raw, 4, 0)
        raw[11] &= 0xF0
        self._set_mode(raw, getattr(memory, "mode", "FM"))
        self._encode_tone(memory, raw)
        if memory.tuning_step in STEPS:
            raw[14] = STEPS.index(memory.tuning_step)
        else:
            raw[14] = STEPS.index(12.5)
        # The RX-only firmware ignores TX fields, but keeping TXLock set in
        # every channel also protects images shared with non-RX-only tools.
        raw[12] |= 0x40
        self._set_mmap_bytes(offset, raw)

        if not special:
            name_text = str(getattr(memory, "name", ""))
            if self._supports_external_japanese():
                encoded = _validate_japanese_name(name_text)
                if any(ord(character) > 0x7E for character in name_text):
                    self._set_external_name(index, encoded)
                    self._set_mmap_bytes(
                        self._name_offset(index), b"\x00" * 16)
                else:
                    if len(name_text) > 10:
                        raise errors.RadioError(
                            "ASCII channel names remain limited to 10 characters")
                    self._set_mmap_bytes(
                        self._name_offset(index), encoded.ljust(16, b"\x00"))
                    self._clear_external_name(index)
            else:
                name = name_text.encode("ascii", errors="ignore")[:10]
                self._set_mmap_bytes(
                    self._name_offset(index), name.ljust(16, b"\x00"))

        self._set_band(special, index, band)
        self._set_scanlists(special, index,
                            self._scanlist_value(memory,
                                                 self._get_scanlists(special,
                                                                     index)))
        return memory

    def get_settings(self):
        basic = RadioSettingGroup("basic", "基本設定")
        display = RadioSettingGroup("display", "表示・操作")
        keys = RadioSettingGroup("keys", "プログラマブルキー")
        scan = RadioSettingGroup("scan", "スキャン設定")
        f4hwn = RadioSettingGroup("f4hwn", "F4HWN受信設定")
        logo = RadioSettingGroup("logo", "起動画面ロゴ")
        group = RadioSettingGroup("fm", "FM放送受信")

        settings_base = self.PROFILE.settings_base
        action_base = self.PROFILE.action_settings_base
        scan_base = self.PROFILE.scan_settings_base
        f4hwn_base = self.PROFILE.f4hwn_base

        main = bytes(self._mmap[settings_base:settings_base + 16])
        actions = bytes(self._mmap[action_base:action_base + 0x50])
        scan_data = bytes(self._mmap[scan_base:scan_base + 8])
        f4_data = bytes(self._mmap[f4hwn_base:f4hwn_base + 8])

        squelch = main[1] if main[1] < 10 else 1
        basic.append(RadioSetting(
            "squelch", "スケルチ",
            RadioSettingValueInteger(0, 9, squelch)))
        self._append_list_setting(
            basic, "channel_display_mode", "チャンネル表示",
            CHANNEL_DISPLAY_LIST, main[9] if main[9] < 4 else 0)
        self._append_list_setting(
            basic, "battery_save", "バッテリーセーブ",
            BATTERY_SAVE_LIST, main[11] if main[11] < 6 else 4)
        self._append_list_setting(
            basic, "dual_watch", "デュアル受信",
            DUAL_WATCH_LIST, main[12] if main[12] < 3 else 1)
        backlight_time = main[13] if main[13] < len(BACKLIGHT_LIST) else 12
        self._append_list_setting(
            basic, "backlight_time", "バックライト時間",
            BACKLIGHT_LIST, backlight_time)
        self._append_list_setting(
            basic, "scan_resume_mode", "スキャン再開",
            SCAN_RESUME_LIST, actions[5] if actions[5] < 105 else 14)
        self._append_list_setting(
            basic, "power_on_display_mode", "起動画面",
            POWER_ON_DISPLAY_LIST, actions[7] if actions[7] < 8 else 3)
        self._append_list_setting(
            basic, "battery_type", "バッテリー種別",
            BATTERY_TYPE_LIST, actions[0x1C] if actions[0x1C] < 5 else 0)

        backlight_max = main[8] & 0x0F
        if backlight_max > 10:
            backlight_max = 10
        backlight_min = main[8] >> 4
        if backlight_min >= backlight_max:
            backlight_min = 0
        display.append(RadioSetting(
            "backlight_min", "バックライト最低輝度",
            RadioSettingValueInteger(0, 10, backlight_min)))
        display.append(RadioSetting(
            "backlight_max", "バックライト最高輝度",
            RadioSettingValueInteger(0, 10, backlight_max)))
        contrast = f4_data[5] & 0x0F
        if contrast == 0 or contrast >= 16:
            contrast = 10
        display.append(RadioSetting(
            "contrast", "コントラスト",
            RadioSettingValueInteger(1, 15, contrast)))
        display.append(RadioSetting(
            "invert_display", "表示反転",
            RadioSettingValueBoolean(bool(f4_data[5] & 0x10))))
        self._append_list_setting(
            display, "meter_style", "Sメーター表示",
            METER_LIST, 1 if f4_data[5] & 0x40 else 0)
        display.append(RadioSetting(
            "gui_style", "GUI表示",
            RadioSettingValueBoolean(bool(f4_data[5] & 0x80))))
        self._append_list_setting(
            display, "menu_lock_mode", "メニューロック範囲",
            MENU_LOCK_LIST, f4_data[2] if f4_data[2] < 4 else 0)
        sleep_timer = f4_data[4] >> 1
        if sleep_timer > 120:
            sleep_timer = 60
        self._append_list_setting(
            display, "sleep_timer", "スリープタイマー",
            SLEEP_TIMER_LIST, sleep_timer)
        display.append(RadioSetting(
            "beep_control", "キービープ",
            RadioSettingValueBoolean(bool(actions[0] & 0x01))))
        display.append(RadioSetting(
            "key_lock", "キーロック",
            RadioSettingValueBoolean(bool(main[4] & 0x01))))
        auto_lock = actions[6] if actions[6] < len(AUTO_KEYPAD_LOCK_LIST) else 0
        self._append_list_setting(
            display, "auto_keypad_lock", "自動キーロック",
            AUTO_KEYPAD_LOCK_LIST, auto_lock)

        for name, label, raw in (
                ("key1_shortpress_action", "サイドキー1 短押し", actions[1]),
                ("key1_longpress_action", "サイドキー1 長押し", actions[2]),
                ("key2_shortpress_action", "サイドキー2 短押し", actions[3]),
                ("key2_longpress_action", "サイドキー2 長押し", actions[4]),
                ("keyM_longpress_action", "［M］長押し", actions[0] >> 1)):
            self._append_list_setting(
                keys, name, label, ACTION_LIST,
                raw if raw < len(ACTION_LIST) else 0)

        scan_default = scan_data[0] & 0x7F
        if not 1 <= scan_default <= len(SCAN_LIST_CHOICES):
            scan_default = 1
        self._append_list_setting(
            scan, "scan_list_default", "標準スキャンリスト",
            SCAN_LIST_CHOICES, scan_default - 1)
        scan.append(RadioSetting(
            "scan_list_enabled", "標準スキャンリストを有効化",
            RadioSettingValueBoolean(bool(scan_data[0] & 0x80))))
        for name, label, offset in (
                ("priority_channel_1", "優先チャンネル1", 1),
                ("priority_channel_2", "優先チャンネル2", 3),
                ("call_channel", "コールチャンネル", 5)):
            channel = _u16(scan_data, offset)
            channel_value = channel + 1 if channel < self.PROFILE.memory_channels else 0
            scan.append(RadioSetting(
                name, "%s（0=未設定）" % label,
                RadioSettingValueInteger(0, self.PROFILE.memory_channels,
                                         channel_value)))

        self._append_list_setting(
            f4hwn, "audio_fm", "FM受信音声プロファイル",
            FM_AUDIO_LIST, main[0] & 0x0F)
        self._append_list_setting(
            f4hwn, "audio_am", "AM受信音声プロファイル",
            AM_AUDIO_LIST, (main[0] >> 4) & 0x0F)
        f4hwn.append(RadioSetting(
            "nfm_narrower", "NFMナロー化",
            RadioSettingValueBoolean(bool(main[14] & 0x02))))

        for index in range(2):
            raw = bytes(self._mmap[self.PROFILE.logo_base + index * 16:
                                   self.PROFILE.logo_base + (index + 1) * 16])
            logo.append(RadioSetting(
                "logo_%d" % (index + 1), "ロゴ%d（ASCII 16文字）" % (index + 1),
                RadioSettingValueString(0, 16, self._ascii_value(raw))))

        cfg = bytes(self._mmap[self.PROFILE.fm_cfg:
                               self.PROFILE.fm_cfg + 4])
        current = _u16(cfg, 0)
        if not FM_MIN <= current <= FM_MAX:
            current = FM_MIN
        setting = RadioSetting(
            "fm_current", "現在周波数 (0.1 MHz)",
            RadioSettingValueInteger(FM_MIN, FM_MAX, current))
        group.append(setting)
        for channel in range(self.PROFILE.fm_count):
            value = self._get_mmap_u16(self.PROFILE.fm_channels + channel * 2)
            if value == 0xFFFF or not FM_MIN <= value <= FM_MAX:
                value = 0
            group.append(RadioSetting(
                "fm_%02d" % (channel + 1),
                "FM %02d (0=空き, 0.1 MHz)" % (channel + 1),
                RadioSettingValueInteger(0, FM_MAX, value)))
        # CHIRP's Settings tab consumes an explicit list of groups.  Build it
        # the same way as the F4HWN drivers so every group remains visible;
        # passing groups through a constructor is not supported consistently
        # by older CHIRP releases.
        result = RadioSettings()
        for setting_group in (basic, display, keys, scan, f4hwn, logo, group):
            result.append(setting_group)
        return result

    def set_settings(self, settings):
        values = {}
        self._collect_settings(settings, values)

        settings_base = self.PROFILE.settings_base
        action_base = self.PROFILE.action_settings_base
        scan_base = self.PROFILE.scan_settings_base
        f4hwn_base = self.PROFILE.f4hwn_base
        main = bytearray(self._mmap[settings_base:settings_base + 16])
        actions = bytearray(self._mmap[action_base:action_base + 0x50])
        scan_data = bytearray(self._mmap[scan_base:scan_base + 8])
        f4_data = bytearray(self._mmap[f4hwn_base:f4hwn_base + 8])

        if "audio_fm" in values:
            audio_fm = self._choice_index(values["audio_fm"], FM_AUDIO_LIST,
                                          "audio_fm")
        else:
            audio_fm = main[0] & 0x0F
        if "audio_am" in values:
            audio_am = self._choice_index(values["audio_am"], AM_AUDIO_LIST,
                                          "audio_am")
        else:
            audio_am = (main[0] >> 4) & 0x0F
        main[0] = (audio_fm & 0x0F) | ((audio_am & 0x0F) << 4)

        if "squelch" in values:
            main[1] = self._int_value(values["squelch"], "squelch", 0, 9)
        if "channel_display_mode" in values:
            main[9] = self._choice_index(
                values["channel_display_mode"], CHANNEL_DISPLAY_LIST,
                "channel_display_mode")
        if "battery_save" in values:
            main[11] = self._choice_index(
                values["battery_save"], BATTERY_SAVE_LIST, "battery_save")
        if "dual_watch" in values:
            main[12] = self._choice_index(
                values["dual_watch"], DUAL_WATCH_LIST, "dual_watch")
        if "backlight_time" in values:
            main[13] = self._choice_index(
                values["backlight_time"], BACKLIGHT_LIST, "backlight_time")
        if "nfm_narrower" in values:
            main[14] = (main[14] & ~0x02) | \
                (self._bool_value(values["nfm_narrower"]) << 1)
        if "key_lock" in values:
            main[4] = (main[4] & ~0x01) | self._bool_value(values["key_lock"])
        if "backlight_min" in values:
            backlight_min = self._int_value(
                values["backlight_min"], "backlight_min", 0, 10)
        else:
            backlight_min = main[8] >> 4
        if "backlight_max" in values:
            backlight_max = self._int_value(
                values["backlight_max"], "backlight_max", 0, 10)
        else:
            backlight_max = main[8] & 0x0F
        if backlight_min > backlight_max:
            raise errors.RadioError("backlight_min must not exceed backlight_max")
        main[8] = (backlight_min << 4) | backlight_max

        if "beep_control" in values:
            actions[0] = (actions[0] & ~0x01) | \
                self._bool_value(values["beep_control"])
        action_names = (
            "key1_shortpress_action", "key1_longpress_action",
            "key2_shortpress_action", "key2_longpress_action")
        for index, name in enumerate(action_names, 1):
            if name in values:
                action = self._choice_index(values[name], ACTION_LIST, name)
                actions[index] = action
        if "keyM_longpress_action" in values:
            action = self._choice_index(
                values["keyM_longpress_action"], ACTION_LIST,
                "keyM_longpress_action")
            actions[0] = (actions[0] & 0x01) | (action << 1)
        if "scan_resume_mode" in values:
            actions[5] = self._choice_index(
                values["scan_resume_mode"], SCAN_RESUME_LIST,
                "scan_resume_mode")
        if "auto_keypad_lock" in values:
            actions[6] = self._choice_index(
                values["auto_keypad_lock"], AUTO_KEYPAD_LOCK_LIST,
                "auto_keypad_lock")
        if "power_on_display_mode" in values:
            actions[7] = self._choice_index(
                values["power_on_display_mode"], POWER_ON_DISPLAY_LIST,
                "power_on_display_mode")
        if "battery_type" in values:
            actions[0x1C] = self._choice_index(
                values["battery_type"], BATTERY_TYPE_LIST, "battery_type")

        if "scan_list_default" in values:
            scan_list = self._choice_index(
                values["scan_list_default"], SCAN_LIST_CHOICES,
                "scan_list_default") + 1
            scan_data[0] = (scan_data[0] & 0x80) | (scan_list & 0x7F)
        if "scan_list_enabled" in values:
            scan_data[0] = (scan_data[0] & ~0x80) | \
                (self._bool_value(values["scan_list_enabled"]) << 7)
        for name, offset in (
                ("priority_channel_1", 1),
                ("priority_channel_2", 3),
                ("call_channel", 5)):
            if name not in values:
                continue
            channel = self._int_value(
                values[name], name, 0, self.PROFILE.memory_channels)
            raw = self.PROFILE.memory_channels if channel == 0 else channel - 1
            _put_u16(scan_data, offset, raw)

        if "contrast" in values:
            contrast = self._int_value(values["contrast"], "contrast", 1, 15)
            f4_data[5] = (f4_data[5] & 0xF0) | contrast
        for name, mask in (("invert_display", 0x10), ("gui_style", 0x80)):
            if name in values:
                if self._bool_value(values[name]):
                    f4_data[5] |= mask
                else:
                    f4_data[5] &= ~mask
        if "meter_style" in values:
            meter = self._choice_index(values["meter_style"], METER_LIST,
                                       "meter_style")
            if meter:
                f4_data[5] |= 0x40
            else:
                f4_data[5] &= ~0x40
        if "menu_lock_mode" in values:
            f4_data[2] = self._choice_index(
                values["menu_lock_mode"], MENU_LOCK_LIST, "menu_lock_mode")
        if "sleep_timer" in values:
            sleep_timer = self._choice_index(
                values["sleep_timer"], SLEEP_TIMER_LIST, "sleep_timer")
            f4_data[4] = (f4_data[4] & 0x01) | (sleep_timer << 1)

        self._set_mmap_bytes(settings_base, main)
        self._set_mmap_bytes(action_base, actions)
        self._set_mmap_bytes(scan_base, scan_data)
        self._set_mmap_bytes(f4hwn_base, f4_data)

        # The logo is inside the action/settings sector.  Write it after the
        # sector-level updates so that the read-modify-write of the action
        # block cannot restore the previous logo bytes.
        for index in range(2):
            name = "logo_%d" % (index + 1)
            if name not in values:
                continue
            try:
                encoded = str(values[name]).encode("ascii")
            except UnicodeEncodeError as exc:
                raise errors.RadioError("Logo must contain ASCII characters") from exc
            if len(encoded) > 16:
                raise errors.RadioError("Logo is limited to 16 ASCII characters")
            self._set_mmap_bytes(
                self.PROFILE.logo_base + index * 16,
                encoded.ljust(16, b"\x00"))

        for name, value_object in values.items():
            if name == "fm_current":
                value = self._int_value(value_object, name)
                if not FM_MIN <= value <= FM_MAX:
                    raise errors.RadioError("FM frequency must be 76.0-95.0 MHz")
                self._set_mmap_u16(self.PROFILE.fm_cfg, value)
                cfg = bytearray(self._mmap[self.PROFILE.fm_cfg:
                                           self.PROFILE.fm_cfg + 4])
                cfg[3] = (cfg[3] & 0xF9) | 0x02  # hardware band 76-108 MHz
                self._set_mmap_bytes(self.PROFILE.fm_cfg, cfg)
            elif name.startswith("fm_"):
                channel = int(name[3:]) - 1
                if not 0 <= channel < self.PROFILE.fm_count:
                    raise errors.RadioError("Invalid FM channel")
                value = self._int_value(value_object, name)
                if value != 0 and not FM_MIN <= value <= FM_MAX:
                    raise errors.RadioError("FM channel must be 76.0-95.0 MHz")
                self._set_mmap_u16(
                    self.PROFILE.fm_channels + channel * 2,
                    0xFFFF if value == 0 else value)


@directory.register
class WRXJPUVK1K5V3(_WRXJPBase):
    """UV-K1 and UV-K5 V3 (same PY32F071 profile)."""

    VENDOR = "Quansheng"
    MODEL = "UV-K1 / UV-K5 V3 (wrx-jp RX-only)"
    PROFILE = PY32_PROFILE
