/* Static display text for the WRX-JP build. */
#ifndef APP_UI_JP_TEXT_H
#define APP_UI_JP_TEXT_H

#include "jp_vocab.h"

/* The Japanese build uses the compact internal one-byte code set for static
 * UI text.  Protocol names (FM, DCS, USB, etc.) remain ASCII by design. */
#ifdef ENABLE_JAPANESE
#define WRX_UI_TEXT_FM_ONLY          "FM\x98\x99"
#define WRX_UI_TEXT_LOW_BATTERY      "\x8F\xF7 LOW"
#define WRX_UI_TEXT_UNLOCK_KEYBOARD  "\xB7\xE0 LOCK"
#define WRX_UI_TEXT_PRESS_EXIT       "EXIT"
#define WRX_UI_TEXT_SCAN_LIST        WRX_JP_SCAN " "
#define WRX_UI_TEXT_ITEMS            "NUM"
#define WRX_UI_TEXT_NONE             "\x97"
#define WRX_UI_TEXT_VFO_TX_DISABLED  "\x80\x81\x98\x99"
#define WRX_UI_TEXT_SCAN_RANGE       WRX_JP_SCAN
#define WRX_UI_TEXT_OK_QUESTION      "OK?"
#define WRX_UI_TEXT_WAIT             "WAIT"
#define WRX_UI_TEXT_SCAN_STOP        "STOP"
#define WRX_UI_TEXT_SCAN_CARRIER     "CARRIER"
#define WRX_UI_TEXT_SCAN_TIMEOUT     "TIMEOUT"
#define WRX_UI_TEXT_FM_SAVE          "\x86\x87?"
#define WRX_UI_TEXT_FM_DELETE        "\x88\x89?"
#define WRX_UI_TEXT_SAVE_PREFIX      "\x86\x87:"
#define WRX_UI_TEXT_FREQ_PREFIX      "\xF2\xF3\xF4:"
#define WRX_UI_TEXT_TONE_PREFIX      "\xC4\xE0\xDD:"
#define WRX_UI_TEXT_PRESET_APPLY     "M OK  *SCAN"
#define WRX_UI_TEXT_PRESET_CANCEL    "EXIT"
#define WRX_UI_TEXT_FM_VFO           "VFO"
#define WRX_UI_TEXT_FM_MANUAL_SCAN   "M-SCAN"
#define WRX_UI_TEXT_FM_AUTO_SCAN     "A-SCAN"
#define WRX_UI_TEXT_STEP             "\xBD\xC3\xAF\xCC\xDF"
#define WRX_UI_TEXT_RX_PRESET        "\x80\x81\xF5\xF6"
#define WRX_UI_TEXT_RX_EXT_OFF       "\x80\x81\xE1\xE2 OFF"
#define WRX_UI_TEXT_PRESET_ERROR     "ERROR"
#define WRX_UI_TEXT_VFO_ONLY         "VFO ONLY"
#define WRX_UI_TEXT_SCAN_ACTIVE      "SCAN ACTIVE"
#define WRX_UI_TEXT_REV_ON           "REV ON"
#define WRX_UI_TEXT_DUAL_RX_ON       "DUAL RX ON"
#define WRX_UI_TEXT_CROSS_ON         "CROSS ON"
#define WRX_UI_TEXT_FM_MODE          "FM MODE"
#define WRX_UI_TEXT_SEARCH_FREQ      "\xF2\xF3\xF4"
#define WRX_UI_TEXT_SEARCH_TONE      "\xC4\xE0\xDD"
#define WRX_UI_TEXT_SCAN_COMPLETE    "OK"
#define WRX_UI_TEXT_SCAN_FAILED       "NG"
#else
#define WRX_UI_TEXT_FM_ONLY          "FM ONLY"
#define WRX_UI_TEXT_LOW_BATTERY      "LOW BATTERY"
#define WRX_UI_TEXT_UNLOCK_KEYBOARD  "UNLOCK KEYBOARD"
#define WRX_UI_TEXT_PRESS_EXIT       "Press EXIT"
#define WRX_UI_TEXT_SCAN_LIST        "SCAN LIST "
#define WRX_UI_TEXT_ITEMS            "items"
#define WRX_UI_TEXT_NONE             "None"
#define WRX_UI_TEXT_VFO_TX_DISABLED  "TX DISABLE"
#define WRX_UI_TEXT_SCAN_RANGE       "ScnRng"
#define WRX_UI_TEXT_OK_QUESTION      "SURE?"
#define WRX_UI_TEXT_WAIT             "WAIT!"
#define WRX_UI_TEXT_SCAN_STOP        "STOP"
#define WRX_UI_TEXT_SCAN_CARRIER     "CARRIER"
#define WRX_UI_TEXT_SCAN_TIMEOUT     "TIMEOUT"
#define WRX_UI_TEXT_FM_SAVE          "SAVE?"
#define WRX_UI_TEXT_FM_DELETE        "DEL?"
#define WRX_UI_TEXT_SAVE_PREFIX      "Save:"
#define WRX_UI_TEXT_FREQ_PREFIX      "Freq:"
#define WRX_UI_TEXT_TONE_PREFIX      "Tone:"
#define WRX_UI_TEXT_PRESET_APPLY     "M APPLY  * SCAN"
#define WRX_UI_TEXT_PRESET_CANCEL    "EXIT CANCEL"
#define WRX_UI_TEXT_FM_VFO           "VFO"
#define WRX_UI_TEXT_FM_MANUAL_SCAN   "M-SCAN"
#define WRX_UI_TEXT_FM_AUTO_SCAN     "A-SCAN"
#define WRX_UI_TEXT_STEP             "Step"
#define WRX_UI_TEXT_RX_PRESET        "RX PRESET"
#define WRX_UI_TEXT_RX_EXT_OFF       "RXExt OFF"
#define WRX_UI_TEXT_PRESET_ERROR     "PRESET ERROR"
#define WRX_UI_TEXT_VFO_ONLY         "VFO ONLY"
#define WRX_UI_TEXT_SCAN_ACTIVE      "SCAN ACTIVE"
#define WRX_UI_TEXT_REV_ON           "REV ON"
#define WRX_UI_TEXT_DUAL_RX_ON       "DUAL RX ON"
#define WRX_UI_TEXT_CROSS_ON         "CROSS ON"
#define WRX_UI_TEXT_FM_MODE          "FM MODE"
#define WRX_UI_TEXT_SEARCH_FREQ      "Search Freq"
#define WRX_UI_TEXT_SEARCH_TONE      "Search Tone"
#define WRX_UI_TEXT_SCAN_COMPLETE    "Scan Complete"
#define WRX_UI_TEXT_SCAN_FAILED      "Scan Failed"
#endif

#endif
