/* Static display text for the WRX-JP build. */
#ifndef APP_UI_JP_TEXT_H
#define APP_UI_JP_TEXT_H

/* Static labels use ASCII so they remain legible without an uploaded font.
 * User-provided channel names can still use the external Unicode bitmap. */
#define WRX_UI_TEXT_FM_ONLY          "FM ONLY"
#define WRX_UI_TEXT_LOW_BATTERY      "LOW BATTERY"
#define WRX_UI_TEXT_UNLOCK_KEYBOARD  "KEY LOCK"
#define WRX_UI_TEXT_PRESS_EXIT       "EXIT"
#define WRX_UI_TEXT_SCAN_LIST        "SCAN LIST "
#define WRX_UI_TEXT_ITEMS            "ITEMS"
#define WRX_UI_TEXT_NONE             "NONE"
#define WRX_UI_TEXT_VFO_TX_DISABLED  "RX ONLY"
#define WRX_UI_TEXT_SCAN_RANGE       "SCAN"
#define WRX_UI_TEXT_OK_QUESTION      "OK?"
#define WRX_UI_TEXT_WAIT             "WAIT"
#define WRX_UI_TEXT_SCAN_STOP        "STOP"
#define WRX_UI_TEXT_SCAN_CARRIER     "CARRIER"
#define WRX_UI_TEXT_SCAN_TIMEOUT     "TIMEOUT"
#define WRX_UI_TEXT_FM_SAVE          "SAVE?"
#define WRX_UI_TEXT_FM_DELETE        "DELETE?"
#define WRX_UI_TEXT_SAVE_PREFIX      "SAVE:"
#define WRX_UI_TEXT_FREQ_PREFIX      "FREQ:"
#define WRX_UI_TEXT_TONE_PREFIX      "TONE:"
#define WRX_UI_TEXT_PRESET_APPLY     "M APPLY *SCAN"
#define WRX_UI_TEXT_PRESET_CANCEL    "EXIT"
#define WRX_UI_TEXT_FM_VFO           "VFO"
#define WRX_UI_TEXT_FM_MANUAL_SCAN   "M-SCAN"
#define WRX_UI_TEXT_FM_AUTO_SCAN     "A-SCAN"
#define WRX_UI_TEXT_STEP             "STEP"
#define WRX_UI_TEXT_RX_PRESET        "RX PRESET"
#define WRX_UI_TEXT_RX_EXT_OFF       "RX EXT OFF"
#define WRX_UI_TEXT_PRESET_ERROR     "PRESET FAIL"
#define WRX_UI_TEXT_VFO_ONLY         "VFO ONLY"
#define WRX_UI_TEXT_SCAN_ACTIVE      "SCAN ACTIVE"
#define WRX_UI_TEXT_REV_ON           "REV ON"
#define WRX_UI_TEXT_DUAL_RX_ON       "DUAL RX ON"
#define WRX_UI_TEXT_CROSS_ON         "CROSS ON"
#define WRX_UI_TEXT_FM_MODE          "FM MODE"
#define WRX_UI_TEXT_SEARCH_FREQ      "FREQ"
#define WRX_UI_TEXT_SEARCH_TONE      "TONE"
#define WRX_UI_TEXT_SCAN_COMPLETE    "SCAN OK"
#define WRX_UI_TEXT_SCAN_FAILED      "SCAN FAIL"

#endif
