/* Fixed-size 1bit category icons for the K1 LCD menu. */
#ifndef UI_MENU_ICONS_H
#define UI_MENU_ICONS_H

#include <stdint.h>

#define UI_MENU_ICON_WIDTH       40u
#define UI_MENU_ICON_HEIGHT      32u
#define UI_MENU_ICON_ROW_BYTES   5u

#define UI_MENU_ICON_DECL(name) \
    extern const uint8_t name[UI_MENU_ICON_HEIGHT][UI_MENU_ICON_ROW_BYTES]

UI_MENU_ICON_DECL(UI_MENU_ICON_CHANNELS);
UI_MENU_ICON_DECL(UI_MENU_ICON_SCAN);
UI_MENU_ICON_DECL(UI_MENU_ICON_KEYS);
UI_MENU_ICON_DECL(UI_MENU_ICON_POWER);
UI_MENU_ICON_DECL(UI_MENU_ICON_DISPLAY);
UI_MENU_ICON_DECL(UI_MENU_ICON_TIMERS);
UI_MENU_ICON_DECL(UI_MENU_ICON_AUDIO);
UI_MENU_ICON_DECL(UI_MENU_ICON_RADIO);
UI_MENU_ICON_DECL(UI_MENU_ICON_DTMF);
UI_MENU_ICON_DECL(UI_MENU_ICON_SERVICE);
UI_MENU_ICON_DECL(UI_MENU_ICON_ALL);

#endif /* UI_MENU_ICONS_H */

