/*
 * WRX-JP menu text catalog
 *
 * Edit the display labels and the receive-only help strings in this file.
 * Menu order, IDs, and behavior remain in menu.c.  Each label must fit the
 * six-character menu field (the surrounding array reserves seven bytes for
 * the terminating NUL).  Static labels use ASCII so the menu remains legible
 * before a font upload.
 */

#ifndef APP_UI_MENU_TEXT_H
#define APP_UI_MENU_TEXT_H

#ifdef ENABLE_JAPANESE
#define WRX_MENU_LABEL_STEP             "Step"
#define WRX_MENU_LABEL_RX_DCS           "RxDCS"
#define WRX_MENU_LABEL_RX_CTCS          "RxCTCS"
#define WRX_MENU_LABEL_W_N              "W/N"
#define WRX_MENU_LABEL_RX_EXT           "RXExt"
#define WRX_MENU_LABEL_RX_BANK          "RxBank"
#define WRX_MENU_LABEL_RX_BANK_SET      "BnkSet"
#define WRX_MENU_LABEL_MODULATION       "Mode"
#define WRX_MENU_LABEL_CHANNEL_LIST     "ChList"
#define WRX_MENU_LABEL_SAVE_CHANNEL     "ChSave"
#define WRX_MENU_LABEL_DELETE_CHANNEL   "ChDel"
#define WRX_MENU_LABEL_CHANNEL_NAME     "ChName"
#define WRX_MENU_LABEL_SCAN_LIST        "ScList"
#define WRX_MENU_LABEL_PRIORITY         "ScPri"
#define WRX_MENU_LABEL_PRIORITY1        "PriCh1"
#define WRX_MENU_LABEL_PRIORITY2        "PriCh2"
#define WRX_MENU_LABEL_F1_SHORT         "F1Shrt"
#define WRX_MENU_LABEL_F1_LONG          "F1Long"
#define WRX_MENU_LABEL_F2_SHORT         "F2Shrt"
#define WRX_MENU_LABEL_F2_LONG          "F2Long"
#define WRX_MENU_LABEL_M_LONG           "M Long"
#define WRX_MENU_LABEL_KEY_LOCK         "KeyLck"
#define WRX_MENU_LABEL_BATTERY_SAVE     "BatSav"
#define WRX_MENU_LABEL_BATTERY_TEXT     "BatTxt"
#define WRX_MENU_LABEL_CHANNEL_DISPLAY  "ChDisp"
#define WRX_MENU_LABEL_POWER_ON         "POnMsg"
#define WRX_MENU_LABEL_BACKLIGHT        "BLTime"
#define WRX_MENU_LABEL_BACKLIGHT_MIN    "BLMin"
#define WRX_MENU_LABEL_BACKLIGHT_MAX    "BLMax"
#define WRX_MENU_LABEL_BEEP             "Beep"
#define WRX_MENU_LABEL_INFO             "SysInf"
#define WRX_MENU_LABEL_BATTERY_VOLTAGE  "BatVol"
#define WRX_MENU_LABEL_RX_MODE          "RxMode"
#define WRX_MENU_LABEL_SQUELCH          "Sql"
#define WRX_MENU_LABEL_SET_INV          "SetInv"
#define WRX_MENU_LABEL_SET_MENU_LOCK    "SetLck"
#define WRX_MENU_LABEL_SET_METER        "SetMet"
#define WRX_MENU_LABEL_SET_GUI          "SetGUI"
#define WRX_MENU_LABEL_SET_MAIN_FONT    "JpFont"
#define WRX_MENU_LABEL_SET_AUDIO        "SetRxA"
#define WRX_MENU_LABEL_SET_SLEEP        "SetOff"
#define WRX_MENU_LABEL_SET_NFM          "SetNFM"
#define WRX_MENU_LABEL_SET_VOLUME       "SetVol"
#define WRX_MENU_LABEL_SET_SCAN         "SetScn"
#define WRX_MENU_LABEL_SET_SAVE         "SetSav"
#define WRX_MENU_LABEL_BATTERY_CAL      "BatCal"
#define WRX_MENU_LABEL_BATTERY_TYPE     "BatTyp"
#define WRX_MENU_LABEL_RESET            "Reset"
#define WRX_MENU_LABEL_COMPANDER        {'C', 'M', 'P'}
#define WRX_MENU_LABEL_SCAN_REVERSE     "ScnRev"
#define WRX_MENU_LABEL_DTMF_LIVE        {'D', 'T', 'M', 'F'}
#define WRX_MENU_LABEL_SET_CONTRAST     "SetCtr"
#else
#define WRX_MENU_LABEL_STEP             "Step"
#define WRX_MENU_LABEL_RX_DCS           "RxDCS"
#define WRX_MENU_LABEL_RX_CTCS          "RxCTCS"
#define WRX_MENU_LABEL_W_N             "W/N"
#define WRX_MENU_LABEL_RX_EXT           "RXExt"
#define WRX_MENU_LABEL_RX_BANK_SET      "BnkSet"
#define WRX_MENU_LABEL_MODULATION       "Mode"
#define WRX_MENU_LABEL_CHANNEL_LIST     "ChList"
#define WRX_MENU_LABEL_SAVE_CHANNEL     "ChSave"
#define WRX_MENU_LABEL_DELETE_CHANNEL   "ChDele"
#define WRX_MENU_LABEL_CHANNEL_NAME     "ChName"
#define WRX_MENU_LABEL_SCAN_LIST         "ScList"
#define WRX_MENU_LABEL_PRIORITY         "ScPri"
#define WRX_MENU_LABEL_PRIORITY1        "PriCh1"
#define WRX_MENU_LABEL_PRIORITY2        "PriCh2"
#define WRX_MENU_LABEL_F1_SHORT         "F1Shrt"
#define WRX_MENU_LABEL_F1_LONG          "F1Long"
#define WRX_MENU_LABEL_F2_SHORT         "F2Shrt"
#define WRX_MENU_LABEL_F2_LONG          "F2Long"
#define WRX_MENU_LABEL_M_LONG           "M Long"
#define WRX_MENU_LABEL_KEY_LOCK         "KeyLck"
#define WRX_MENU_LABEL_BATTERY_SAVE     "BatSav"
#define WRX_MENU_LABEL_BATTERY_TEXT     "BatTxt"
#define WRX_MENU_LABEL_CHANNEL_DISPLAY  "ChDisp"
#define WRX_MENU_LABEL_POWER_ON         "POnMsg"
#define WRX_MENU_LABEL_BACKLIGHT        "BLTime"
#define WRX_MENU_LABEL_BACKLIGHT_MIN    "BLMin"
#define WRX_MENU_LABEL_BACKLIGHT_MAX    "BLMax"
#define WRX_MENU_LABEL_BEEP             "Beep"
#define WRX_MENU_LABEL_INFO             "SysInf"
#define WRX_MENU_LABEL_BATTERY_VOLTAGE  "BatVol"
#define WRX_MENU_LABEL_RX_MODE          "RxMode"
#define WRX_MENU_LABEL_SQUELCH          "Sql"
#define WRX_MENU_LABEL_SET_INV          "SetInv"
#define WRX_MENU_LABEL_SET_MENU_LOCK    "SetLck"
#define WRX_MENU_LABEL_SET_METER        "SetMet"
#define WRX_MENU_LABEL_SET_GUI          "SetGUI"
#define WRX_MENU_LABEL_SET_MAIN_FONT    "JpFont"
#define WRX_MENU_LABEL_SET_AUDIO        "SetRxA"
#define WRX_MENU_LABEL_SET_SLEEP        "SetOff"
#define WRX_MENU_LABEL_SET_NFM          "SetNFM"
#define WRX_MENU_LABEL_SET_VOLUME       "SetVol"
#define WRX_MENU_LABEL_SET_SCAN         "SetScn"
#define WRX_MENU_LABEL_SET_SAVE         "SetSav"
#define WRX_MENU_LABEL_BATTERY_CAL      "BatCal"
#define WRX_MENU_LABEL_RESET            "Reset"
#endif

#define WRX_MENU_LABEL_POWER            "Power"
#define WRX_MENU_LABEL_TX_DCS           "TxDCS"
#define WRX_MENU_LABEL_TX_CTCS         "TxCTCS"
#define WRX_MENU_LABEL_TX_OFFSET_DIR   "TxODir"
#define WRX_MENU_LABEL_TX_OFFSET       "TxOffs"
#ifndef WRX_MENU_LABEL_RX_BANK
#define WRX_MENU_LABEL_RX_BANK         "Bank"
#endif
#define WRX_MENU_LABEL_SCRAMBLER       "Scramb"
#define WRX_MENU_LABEL_BUSY_CANCEL     "BusyCL"
#ifndef WRX_MENU_LABEL_COMPANDER
#define WRX_MENU_LABEL_COMPANDER       "Compnd"
#endif
#ifndef WRX_MENU_LABEL_SCAN_REVERSE
#define WRX_MENU_LABEL_SCAN_REVERSE    "ScnRev"
#endif
#define WRX_MENU_LABEL_NOAA_SCAN       "NOAA-S"
#define WRX_MENU_LABEL_TX_TIMEOUT      "TxTOut"
#define WRX_MENU_LABEL_MIC             "Mic"
#define WRX_MENU_LABEL_MIC_BAR         "MicBar"
#define WRX_MENU_LABEL_BACKLIGHT_TXRX  "BLTxRx"
#define WRX_MENU_LABEL_VOICE           "Voice"
#define WRX_MENU_LABEL_ROGER           "Roger"
#define WRX_MENU_LABEL_STE             "STE"
#define WRX_MENU_LABEL_RP_STE          "RP STE"
#define WRX_MENU_LABEL_CALL1           "1 Call"
#define WRX_MENU_LABEL_ALARM           "AlarmT"
#define WRX_MENU_LABEL_ANI             "ANI ID"
#define WRX_MENU_LABEL_UP_CODE         "UPCode"
#define WRX_MENU_LABEL_DOWN_CODE       "DWCode"
#define WRX_MENU_LABEL_PTT_ID          "PTT ID"
#define WRX_MENU_LABEL_DTMF_ST         "D ST"
#define WRX_MENU_LABEL_DTMF_RESPONSE   "D Resp"
#define WRX_MENU_LABEL_DTMF_HOLD       "D Hold"
#define WRX_MENU_LABEL_DTMF_PRE        "D Prel"
#define WRX_MENU_LABEL_DTMF_DECODE     "D Decd"
#define WRX_MENU_LABEL_DTMF_LIST       "D List"
#ifndef WRX_MENU_LABEL_DTMF_LIVE
#define WRX_MENU_LABEL_DTMF_LIVE       "D Live"
#endif
#define WRX_MENU_LABEL_AM_FIX          "AM Fix"
#define WRX_MENU_LABEL_VOX             "VOX"
#ifndef WRX_MENU_LABEL_SET_CONTRAST
#define WRX_MENU_LABEL_SET_CONTRAST    "SetCtr"
#endif
#define WRX_MENU_LABEL_SET_POWER       "SetPwr"
#define WRX_MENU_LABEL_SET_PTT         "SetPTT"
#define WRX_MENU_LABEL_SET_TOT         "SetTOT"
#define WRX_MENU_LABEL_SET_EOT         "SetEOT"
#define WRX_MENU_LABEL_SET_TIMER       "SetTmr"
#define WRX_MENU_LABEL_SET_KEY         "SetKey"
#define WRX_MENU_LABEL_SET_NWR         "SetNWR"
#define WRX_MENU_LABEL_F_LOCK          "F Lock"
#define WRX_MENU_LABEL_TX_200          "Tx 200"
#define WRX_MENU_LABEL_TX_350          "Tx 350"
#define WRX_MENU_LABEL_TX_500          "Tx 500"
#define WRX_MENU_LABEL_350_ENABLE      "350 En"
#define WRX_MENU_LABEL_SCRAMBLER_EN    "ScraEn"
#define WRX_MENU_LABEL_FREQ_CAL        "FrCali"
#ifndef WRX_MENU_LABEL_BATTERY_TYPE
#define WRX_MENU_LABEL_BATTERY_TYPE    "BatTyp"
#endif
#define WRX_MENU_LABEL_SET_NAV         "SetNav"

#define WRX_MENU_HELP_SQL              "AUTO=measure noise"
#define WRX_MENU_HELP_W_N              "W+25 W20 N12 N-6"
#define WRX_MENU_HELP_CHANNEL_LIST     "scan list membership"
#define WRX_MENU_HELP_CTCS             "CT NORMAL/REV"
#define WRX_MENU_HELP_RX_EXT           "RX features master"
#define WRX_MENU_HELP_RX_BANK          "scan bank filter"
#define WRX_MENU_HELP_RX_BANK_SET      "set channel bank"

#define WRX_ACTION_NONE                 "NONE"
#define WRX_ACTION_FLASHLIGHT           "FLASH\nLIGHT"
#define WRX_ACTION_MONITOR              "MONITOR"
#define WRX_ACTION_SCAN                 "SCAN"
#define WRX_ACTION_FM                   "FM"
#define WRX_ACTION_LOCK_KEYPAD          "LOCK\nKEYPAD"
#define WRX_ACTION_VFO_A_B              "VFO A\nVFO B"
#define WRX_ACTION_VFO_MEM              "VFO\nMEM"
#define WRX_ACTION_MODE                 "MODE"
#define WRX_ACTION_RX_MODE              "RX MODE"
#define WRX_ACTION_MAIN_ONLY            "MAIN ONLY"
#define WRX_ACTION_WIDE_NARROW          "W/N"
#define WRX_ACTION_MUTE                 "MUTE"

/* The category header uses the large font. Keep these labels short so the
 * category picker remains legible on the 128-pixel LCD. */
#define WRX_MENU_CATEGORY_CHANNELS     "CHANNELS"
#define WRX_MENU_CATEGORY_SCAN         "SCAN"
#define WRX_MENU_CATEGORY_KEYS         "KEYS"
#define WRX_MENU_CATEGORY_POWER        "POWER"
#define WRX_MENU_CATEGORY_DISPLAY      "DISPLAY"
#define WRX_MENU_CATEGORY_TIMERS       "TIMERS"
#define WRX_MENU_CATEGORY_AUDIO        "AUDIO"
#define WRX_MENU_CATEGORY_RADIO        "RADIO"
#define WRX_MENU_CATEGORY_DTMF         "DTMF"
#define WRX_MENU_CATEGORY_SERVICE      "SERVICE"
#define WRX_MENU_CATEGORY_ALL          "ALL"

#endif
