/* WRX-JPのメニュー文言。動作と項目順はmenu.cで管理する。 */
#ifndef APP_UI_MENU_TEXT_H
#define APP_UI_MENU_TEXT_H

#include "menu_text_ja.h"

/* 日本語ラベルと、フォント未書込み時のフォールバックを同じ項目で管理する。 */
#ifdef ENABLE_JAPANESE
#define WRX_MENU_TEXT(ja, ascii) {ja, ascii}
#else
#define WRX_MENU_TEXT(ja, ascii) {ascii, NULL}
#endif

#define WRX_MENU_LABEL_STEP             WRX_MENU_TEXT(WRX_JA_MENU_LABEL_STEP, "Step")
#define WRX_MENU_LABEL_POWER            WRX_MENU_TEXT(WRX_JA_MENU_LABEL_POWER, "Power")
#define WRX_MENU_LABEL_RX_DCS           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_RX_DCS, "RxDCS")
#define WRX_MENU_LABEL_RX_CTCS          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_RX_CTCS, "RxCTCS")
#define WRX_MENU_LABEL_TX_DCS           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_TX_DCS, "TxDCS")
#define WRX_MENU_LABEL_TX_CTCS          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_TX_CTCS, "TxCTCS")
#define WRX_MENU_LABEL_TX_OFFSET_DIR    WRX_MENU_TEXT(WRX_JA_MENU_LABEL_TX_OFFSET_DIR, "TxODir")
#define WRX_MENU_LABEL_TX_OFFSET        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_TX_OFFSET, "TxOffs")
#define WRX_MENU_LABEL_W_N              WRX_MENU_TEXT(WRX_JA_MENU_LABEL_W_N, "W/N")
#define WRX_MENU_LABEL_RX_EXT           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_RX_EXT, "RXExt")
#define WRX_MENU_LABEL_RX_BANK          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_RX_BANK, "RxBank")
#define WRX_MENU_LABEL_RX_BANK_SET      WRX_MENU_TEXT(WRX_JA_MENU_LABEL_RX_BANK_SET, "BnkSet")
#define WRX_MENU_LABEL_SCRAMBLER        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SCRAMBLER, "Scramb")
#define WRX_MENU_LABEL_BUSY_CANCEL      WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BUSY_CANCEL, "BusyCL")
#define WRX_MENU_LABEL_COMPANDER        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_COMPANDER, "CMP")
#define WRX_MENU_LABEL_MODULATION       WRX_MENU_TEXT(WRX_JA_MENU_LABEL_MODULATION, "Mode")
#define WRX_MENU_LABEL_CHANNEL_LIST     WRX_MENU_TEXT(WRX_JA_MENU_LABEL_CHANNEL_LIST, "ChList")
#define WRX_MENU_LABEL_SAVE_CHANNEL     WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SAVE_CHANNEL, "ChSave")
#define WRX_MENU_LABEL_DELETE_CHANNEL   WRX_MENU_TEXT(WRX_JA_MENU_LABEL_DELETE_CHANNEL, "ChDel")
#define WRX_MENU_LABEL_CHANNEL_NAME     WRX_MENU_TEXT(WRX_JA_MENU_LABEL_CHANNEL_NAME, "ChName")
#define WRX_MENU_LABEL_SCAN_LIST        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SCAN_LIST, "ScList")
#define WRX_MENU_LABEL_PRIORITY         WRX_MENU_TEXT(WRX_JA_MENU_LABEL_PRIORITY, "ScPri")
#define WRX_MENU_LABEL_PRIORITY1        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_PRIORITY1, "PriCh1")
#define WRX_MENU_LABEL_PRIORITY2        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_PRIORITY2, "PriCh2")
#define WRX_MENU_LABEL_SCAN_REVERSE     WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SCAN_REVERSE, "ScnRev")
#define WRX_MENU_LABEL_F1_SHORT         WRX_MENU_TEXT(WRX_JA_MENU_LABEL_F1_SHORT, "F1Shrt")
#define WRX_MENU_LABEL_F1_LONG          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_F1_LONG, "F1Long")
#define WRX_MENU_LABEL_F2_SHORT         WRX_MENU_TEXT(WRX_JA_MENU_LABEL_F2_SHORT, "F2Shrt")
#define WRX_MENU_LABEL_F2_LONG          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_F2_LONG, "F2Long")
#define WRX_MENU_LABEL_M_LONG           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_M_LONG, "M Long")
#define WRX_MENU_LABEL_KEY_LOCK         WRX_MENU_TEXT(WRX_JA_MENU_LABEL_KEY_LOCK, "KeyLck")
#define WRX_MENU_LABEL_TX_TIMEOUT       WRX_MENU_TEXT(WRX_JA_MENU_LABEL_TX_TIMEOUT, "TxTOut")
#define WRX_MENU_LABEL_BATTERY_SAVE     WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BATTERY_SAVE, "BatSav")
#define WRX_MENU_LABEL_BATTERY_TEXT     WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BATTERY_TEXT, "BatTxt")
#define WRX_MENU_LABEL_MIC              WRX_MENU_TEXT(WRX_JA_MENU_LABEL_MIC, "Mic")
#define WRX_MENU_LABEL_MIC_BAR          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_MIC_BAR, "MicBar")
#define WRX_MENU_LABEL_CHANNEL_DISPLAY  WRX_MENU_TEXT(WRX_JA_MENU_LABEL_CHANNEL_DISPLAY, "ChDisp")
#define WRX_MENU_LABEL_POWER_ON         WRX_MENU_TEXT(WRX_JA_MENU_LABEL_POWER_ON, "POnMsg")
#define WRX_MENU_LABEL_BACKLIGHT        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BACKLIGHT, "BLTime")
#define WRX_MENU_LABEL_BACKLIGHT_MIN    WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BACKLIGHT_MIN, "BLMin")
#define WRX_MENU_LABEL_BACKLIGHT_MAX    WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BACKLIGHT_MAX, "BLMax")
#define WRX_MENU_LABEL_BACKLIGHT_TXRX   WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BACKLIGHT_TXRX, "BLTxRx")
#define WRX_MENU_LABEL_BEEP             WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BEEP, "Beep")
#define WRX_MENU_LABEL_VOICE            WRX_MENU_TEXT(WRX_JA_MENU_LABEL_VOICE, "Voice")
#define WRX_MENU_LABEL_ROGER            WRX_MENU_TEXT(WRX_JA_MENU_LABEL_ROGER, "Roger")
#define WRX_MENU_LABEL_STE              WRX_MENU_TEXT(WRX_JA_MENU_LABEL_STE, "STE")
#define WRX_MENU_LABEL_RP_STE           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_RP_STE, "RP STE")
#define WRX_MENU_LABEL_CALL1            WRX_MENU_TEXT(WRX_JA_MENU_LABEL_CALL1, "1 Call")
#define WRX_MENU_LABEL_ALARM            WRX_MENU_TEXT(WRX_JA_MENU_LABEL_ALARM, "AlarmT")
#define WRX_MENU_LABEL_ANI              WRX_MENU_TEXT(WRX_JA_MENU_LABEL_ANI, "ANI ID")
#define WRX_MENU_LABEL_UP_CODE          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_UP_CODE, "UPCode")
#define WRX_MENU_LABEL_DOWN_CODE        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_DOWN_CODE, "DWCode")
#define WRX_MENU_LABEL_PTT_ID           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_PTT_ID, "PTT ID")
#define WRX_MENU_LABEL_DTMF_ST          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_DTMF_ST, "D ST")
#define WRX_MENU_LABEL_DTMF_RESPONSE    WRX_MENU_TEXT(WRX_JA_MENU_LABEL_DTMF_RESPONSE, "D Resp")
#define WRX_MENU_LABEL_DTMF_HOLD        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_DTMF_HOLD, "D Hold")
#define WRX_MENU_LABEL_DTMF_PRE         WRX_MENU_TEXT(WRX_JA_MENU_LABEL_DTMF_PRE, "D Prel")
#define WRX_MENU_LABEL_DTMF_DECODE      WRX_MENU_TEXT(WRX_JA_MENU_LABEL_DTMF_DECODE, "D Decd")
#define WRX_MENU_LABEL_DTMF_LIST        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_DTMF_LIST, "D List")
#define WRX_MENU_LABEL_DTMF_LIVE        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_DTMF_LIVE, "D Live")
#define WRX_MENU_LABEL_AM_FIX           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_AM_FIX, "AM Fix")
#define WRX_MENU_LABEL_VOX              WRX_MENU_TEXT(WRX_JA_MENU_LABEL_VOX, "VOX")
#define WRX_MENU_LABEL_INFO             WRX_MENU_TEXT(WRX_JA_MENU_LABEL_INFO, "SysInf")
#define WRX_MENU_LABEL_BATTERY_VOLTAGE  WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BATTERY_VOLTAGE, "BatVol")
#define WRX_MENU_LABEL_RX_MODE          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_RX_MODE, "RxMode")
#define WRX_MENU_LABEL_SQUELCH          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SQUELCH, "Sql")
#define WRX_MENU_LABEL_SET_POWER        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_POWER, "SetPwr")
#define WRX_MENU_LABEL_SET_PTT          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_PTT, "SetPTT")
#define WRX_MENU_LABEL_SET_TOT          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_TOT, "SetTOT")
#define WRX_MENU_LABEL_SET_EOT          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_EOT, "SetEOT")
#define WRX_MENU_LABEL_SET_CONTRAST     WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_CONTRAST, "SetCtr")
#define WRX_MENU_LABEL_SET_INV          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_INV, "SetInv")
#define WRX_MENU_LABEL_SET_MENU_LOCK    WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_MENU_LOCK, "SetLck")
#define WRX_MENU_LABEL_SET_METER        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_METER, "SetMet")
#define WRX_MENU_LABEL_SET_GUI          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_GUI, "SetGUI")
#define WRX_MENU_LABEL_SET_MAIN_FONT    WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_MAIN_FONT, "JpFont")
#define WRX_MENU_LABEL_SET_AUDIO        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_AUDIO, "SetRxA")
#define WRX_MENU_LABEL_SET_SLEEP        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_SLEEP, "SetOff")
#define WRX_MENU_LABEL_SET_NFM          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_NFM, "SetNFM")
#define WRX_MENU_LABEL_SET_VOLUME       WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_VOLUME, "SetVol")
#define WRX_MENU_LABEL_SET_SCAN         WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_SCAN, "SetScn")
#define WRX_MENU_LABEL_SET_SAVE         WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_SAVE, "SetSav")
#define WRX_MENU_LABEL_SET_TIMER        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_TIMER, "SetTmr")
#define WRX_MENU_LABEL_SET_KEY          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_KEY, "SetKey")
#define WRX_MENU_LABEL_SET_NWR          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_NWR, "SetNWR")
#define WRX_MENU_LABEL_BATTERY_CAL      WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BATTERY_CAL, "BatCal")
#define WRX_MENU_LABEL_BATTERY_TYPE     WRX_MENU_TEXT(WRX_JA_MENU_LABEL_BATTERY_TYPE, "BatTyp")
#define WRX_MENU_LABEL_RESET            WRX_MENU_TEXT(WRX_JA_MENU_LABEL_RESET, "Reset")
#define WRX_MENU_LABEL_F_LOCK           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_F_LOCK, "F Lock")
#define WRX_MENU_LABEL_TX_200           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_TX_200, "Tx 200")
#define WRX_MENU_LABEL_TX_350           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_TX_350, "Tx 350")
#define WRX_MENU_LABEL_TX_500           WRX_MENU_TEXT(WRX_JA_MENU_LABEL_TX_500, "Tx 500")
#define WRX_MENU_LABEL_350_ENABLE       WRX_MENU_TEXT(WRX_JA_MENU_LABEL_350_ENABLE, "350 En")
#define WRX_MENU_LABEL_SCRAMBLER_EN     WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SCRAMBLER_EN, "ScraEn")
#define WRX_MENU_LABEL_FREQ_CAL         WRX_MENU_TEXT(WRX_JA_MENU_LABEL_FREQ_CAL, "FrCali")
#define WRX_MENU_LABEL_SET_NAV          WRX_MENU_TEXT(WRX_JA_MENU_LABEL_SET_NAV, "SetNav")
#define WRX_MENU_LABEL_NOAA_SCAN        WRX_MENU_TEXT(WRX_JA_MENU_LABEL_NOAA_SCAN, "NOAA-S")

#define WRX_MENU_HELP_SQL_ASCII         "AUTO=measure noise"
#define WRX_MENU_HELP_W_N_ASCII         "W+25 W20 N12 N-6"
#define WRX_MENU_HELP_CHANNEL_LIST_ASCII "scan list membership"
#define WRX_MENU_HELP_CTCS_ASCII        "CT NORMAL/REV"
#define WRX_MENU_HELP_RX_EXT_ASCII     "RX features master"
#define WRX_MENU_HELP_RX_BANK_ASCII    "scan bank filter"
#define WRX_MENU_HELP_RX_BANK_SET_ASCII "set channel bank"

#ifdef ENABLE_JAPANESE
#define WRX_MENU_HELP_SQL              WRX_JA_MENU_HELP_SQL
#define WRX_MENU_HELP_W_N              WRX_JA_MENU_HELP_W_N
#define WRX_MENU_HELP_CHANNEL_LIST     WRX_JA_MENU_HELP_CHANNEL_LIST
#define WRX_MENU_HELP_CTCS             WRX_JA_MENU_HELP_CTCS
#define WRX_MENU_HELP_RX_EXT           WRX_JA_MENU_HELP_RX_EXT
#define WRX_MENU_HELP_RX_BANK          WRX_JA_MENU_HELP_RX_BANK
#define WRX_MENU_HELP_RX_BANK_SET      WRX_JA_MENU_HELP_RX_BANK_SET
#else
#define WRX_MENU_HELP_SQL              WRX_MENU_HELP_SQL_ASCII
#define WRX_MENU_HELP_W_N              WRX_MENU_HELP_W_N_ASCII
#define WRX_MENU_HELP_CHANNEL_LIST     WRX_MENU_HELP_CHANNEL_LIST_ASCII
#define WRX_MENU_HELP_CTCS             WRX_MENU_HELP_CTCS_ASCII
#define WRX_MENU_HELP_RX_EXT           WRX_MENU_HELP_RX_EXT_ASCII
#define WRX_MENU_HELP_RX_BANK          WRX_MENU_HELP_RX_BANK_ASCII
#define WRX_MENU_HELP_RX_BANK_SET      WRX_MENU_HELP_RX_BANK_SET_ASCII
#endif

#ifdef ENABLE_JAPANESE
#define WRX_MENU_VALUE_OFF              WRX_JA_MENU_VALUE_OFF
#define WRX_MENU_VALUE_ON               WRX_JA_MENU_VALUE_ON
#define WRX_MENU_VALUE_AUTO             WRX_JA_MENU_VALUE_AUTO
#define WRX_MENU_VALUE_ALL              WRX_JA_MENU_VALUE_ALL
#define WRX_MENU_VALUE_NONE             WRX_JA_MENU_VALUE_NONE
#define WRX_MENU_VALUE_NA               WRX_JA_MENU_VALUE_NA
#define WRX_MENU_VALUE_WIDE             WRX_JA_MENU_VALUE_WIDE
#define WRX_MENU_VALUE_NARROW           WRX_JA_MENU_VALUE_NARROW
#define WRX_MENU_VALUE_MAIN_ONLY        WRX_JA_MENU_VALUE_MAIN_ONLY
#define WRX_MENU_VALUE_DUAL_RX          WRX_JA_MENU_VALUE_DUAL_RX
#define WRX_MENU_VALUE_SINGLE           WRX_JA_MENU_VALUE_SINGLE
#define WRX_MENU_VALUE_FREQ             WRX_JA_MENU_VALUE_FREQ
#define WRX_MENU_VALUE_CHANNEL          WRX_JA_MENU_VALUE_CHANNEL
#define WRX_MENU_VALUE_NUMBER           WRX_JA_MENU_VALUE_NUMBER
#define WRX_MENU_VALUE_CHANNEL_NUMBER   WRX_JA_MENU_VALUE_CHANNEL_NUMBER
#define WRX_MENU_VALUE_NAME             WRX_JA_MENU_VALUE_NAME
#define WRX_MENU_VALUE_USER             WRX_JA_MENU_VALUE_USER
#define WRX_MENU_VALUE_DO_NOTHING       WRX_JA_MENU_VALUE_DO_NOTHING
#define WRX_MENU_VALUE_DO               WRX_JA_MENU_VALUE_DO
#define WRX_MENU_VALUE_NOTHING          WRX_JA_MENU_VALUE_NOTHING
#define WRX_MENU_VALUE_RING             WRX_JA_MENU_VALUE_RING
#define WRX_MENU_VALUE_REPLY            WRX_JA_MENU_VALUE_REPLY
#define WRX_MENU_VALUE_BOTH             WRX_JA_MENU_VALUE_BOTH
#define WRX_MENU_VALUE_FULL             WRX_JA_MENU_VALUE_FULL
#define WRX_MENU_VALUE_MESSAGE          WRX_JA_MENU_VALUE_MESSAGE
#define WRX_MENU_VALUE_VOLTAGE          WRX_JA_MENU_VALUE_VOLTAGE
#define WRX_MENU_VALUE_LOGO             WRX_JA_MENU_VALUE_LOGO
#define WRX_MENU_VALUE_LOGO_MESSAGE     WRX_JA_MENU_VALUE_LOGO_MESSAGE
#define WRX_MENU_VALUE_LOGO_ALL         WRX_JA_MENU_VALUE_LOGO_ALL
#define WRX_MENU_VALUE_SOUND            WRX_JA_MENU_VALUE_SOUND
#define WRX_MENU_VALUE_VISUAL           WRX_JA_MENU_VALUE_VISUAL
#define WRX_MENU_VALUE_SITE             WRX_JA_MENU_VALUE_SITE
#define WRX_MENU_VALUE_TONE             WRX_JA_MENU_VALUE_TONE
#define WRX_MENU_VALUE_UP_CODE          WRX_JA_MENU_VALUE_UP_CODE
#define WRX_MENU_VALUE_DOWN_CODE        WRX_JA_MENU_VALUE_DOWN_CODE
#define WRX_MENU_VALUE_UP_DOWN          WRX_JA_MENU_VALUE_UP_DOWN
#define WRX_MENU_VALUE_CODE             WRX_JA_MENU_VALUE_CODE
#define WRX_MENU_VALUE_KEYS             WRX_JA_MENU_VALUE_KEYS
#define WRX_MENU_VALUE_ACTIONS          WRX_JA_MENU_VALUE_ACTIONS
#define WRX_MENU_VALUE_CLASSIC          WRX_JA_MENU_VALUE_CLASSIC
#define WRX_MENU_VALUE_ONEPUSH          WRX_JA_MENU_VALUE_ONEPUSH
#define WRX_MENU_VALUE_NORMAL           WRX_JA_MENU_VALUE_NORMAL
#define WRX_MENU_VALUE_FAST             WRX_JA_MENU_VALUE_FAST
#define WRX_MENU_VALUE_FLAT             WRX_JA_MENU_VALUE_FLAT
#define WRX_MENU_VALUE_CLEAN            WRX_JA_MENU_VALUE_CLEAN
#define WRX_MENU_VALUE_MID              WRX_JA_MENU_VALUE_MID
#define WRX_MENU_VALUE_BOOST            WRX_JA_MENU_VALUE_BOOST
#define WRX_MENU_VALUE_MAX              WRX_JA_MENU_VALUE_MAX
#define WRX_MENU_VALUE_SHARP            WRX_JA_MENU_VALUE_SHARP
#define WRX_MENU_VALUE_STOCK            WRX_JA_MENU_VALUE_STOCK
#define WRX_MENU_VALUE_OPEN             WRX_JA_MENU_VALUE_OPEN
#define WRX_MENU_VALUE_NARROWER         WRX_JA_MENU_VALUE_NARROWER
#define WRX_MENU_VALUE_TINY             WRX_JA_MENU_VALUE_TINY
#define WRX_MENU_VALUE_KEY_MENU         WRX_JA_MENU_VALUE_KEY_MENU
#define WRX_MENU_VALUE_KEY_UP           WRX_JA_MENU_VALUE_KEY_UP
#define WRX_MENU_VALUE_KEY_DOWN         WRX_JA_MENU_VALUE_KEY_DOWN
#define WRX_MENU_VALUE_KEY_EXIT         WRX_JA_MENU_VALUE_KEY_EXIT
#define WRX_MENU_VALUE_MATRIX           WRX_JA_MENU_VALUE_MATRIX
#define WRX_MENU_VALUE_READ             WRX_JA_MENU_VALUE_READ
#define WRX_MENU_VALUE_MANUAL           WRX_JA_MENU_VALUE_MANUAL
#define WRX_MENU_VALUE_NULL             WRX_JA_MENU_VALUE_NULL
#define WRX_MENU_VALUE_DISABLE          WRX_JA_MENU_VALUE_DISABLE
#define WRX_MENU_VALUE_UNLOCK           WRX_JA_MENU_VALUE_UNLOCK
#define WRX_MENU_VALUE_LEFT             WRX_JA_MENU_VALUE_LEFT
#define WRX_MENU_VALUE_RIGHT            WRX_JA_MENU_VALUE_RIGHT
#define WRX_MENU_VALUE_ROGER            WRX_JA_MENU_VALUE_ROGER
#else
#define WRX_MENU_VALUE_OFF              "OFF"
#define WRX_MENU_VALUE_ON               "ON"
#define WRX_MENU_VALUE_AUTO             "AUTO"
#define WRX_MENU_VALUE_ALL              "ALL"
#define WRX_MENU_VALUE_NONE             "NONE"
#define WRX_MENU_VALUE_NA               "N/A"
#define WRX_MENU_VALUE_WIDE             "WIDE"
#define WRX_MENU_VALUE_NARROW           "NARROW"
#define WRX_MENU_VALUE_MAIN_ONLY        "MAIN ONLY"
#define WRX_MENU_VALUE_DUAL_RX          "DUAL RX"
#define WRX_MENU_VALUE_SINGLE           "SINGLE"
#define WRX_MENU_VALUE_FREQ             "FREQ"
#define WRX_MENU_VALUE_CHANNEL          "CHANNEL"
#define WRX_MENU_VALUE_NUMBER           "NUMBER"
#define WRX_MENU_VALUE_CHANNEL_NUMBER   "CHANNEL NUMBER"
#define WRX_MENU_VALUE_NAME             "NAME"
#define WRX_MENU_VALUE_USER             "USER"
#define WRX_MENU_VALUE_DO_NOTHING       "DO\nNOTHING"
#define WRX_MENU_VALUE_DO               "DO"
#define WRX_MENU_VALUE_NOTHING          "NOTHING"
#define WRX_MENU_VALUE_RING             "RING"
#define WRX_MENU_VALUE_REPLY            "REPLY"
#define WRX_MENU_VALUE_BOTH             "BOTH"
#define WRX_MENU_VALUE_FULL             "FULL"
#define WRX_MENU_VALUE_MESSAGE          "MESSAGE"
#define WRX_MENU_VALUE_VOLTAGE          "VOLTAGE"
#define WRX_MENU_VALUE_LOGO             "LOGO"
#define WRX_MENU_VALUE_LOGO_MESSAGE     "LOGO+MSG"
#define WRX_MENU_VALUE_LOGO_ALL         "LOGO+ALL"
#define WRX_MENU_VALUE_SOUND            "SOUND"
#define WRX_MENU_VALUE_VISUAL           "VISUAL"
#define WRX_MENU_VALUE_SITE             "SITE"
#define WRX_MENU_VALUE_TONE             "TONE"
#define WRX_MENU_VALUE_UP_CODE          "UP CODE"
#define WRX_MENU_VALUE_DOWN_CODE        "DOWN CODE"
#define WRX_MENU_VALUE_UP_DOWN          "UP+DOWN"
#define WRX_MENU_VALUE_CODE             "CODE"
#define WRX_MENU_VALUE_KEYS             "KEYS"
#define WRX_MENU_VALUE_ACTIONS          "ACTIONS"
#define WRX_MENU_VALUE_CLASSIC          "CLASSIC"
#define WRX_MENU_VALUE_ONEPUSH          "ONEPUSH"
#define WRX_MENU_VALUE_NORMAL           "NORMAL"
#define WRX_MENU_VALUE_FAST             "FAST"
#define WRX_MENU_VALUE_FLAT             "FLAT"
#define WRX_MENU_VALUE_CLEAN            "CLEAN"
#define WRX_MENU_VALUE_MID              "MID"
#define WRX_MENU_VALUE_BOOST            "BOOST"
#define WRX_MENU_VALUE_MAX              "MAX"
#define WRX_MENU_VALUE_SHARP            "SHARP"
#define WRX_MENU_VALUE_STOCK            "STOCK"
#define WRX_MENU_VALUE_OPEN             "OPEN"
#define WRX_MENU_VALUE_NARROWER         "NARROWER"
#define WRX_MENU_VALUE_TINY             "TINY"
#define WRX_MENU_VALUE_KEY_MENU         "KEY_MENU"
#define WRX_MENU_VALUE_KEY_UP           "KEY_UP"
#define WRX_MENU_VALUE_KEY_DOWN         "KEY_DOWN"
#define WRX_MENU_VALUE_KEY_EXIT         "KEY_EXIT"
#define WRX_MENU_VALUE_MATRIX           "MATRIX"
#define WRX_MENU_VALUE_READ             "READ"
#define WRX_MENU_VALUE_MANUAL           "MANUAL"
#define WRX_MENU_VALUE_NULL             "NULL"
#define WRX_MENU_VALUE_DISABLE          "DISABLE"
#define WRX_MENU_VALUE_UNLOCK           "UNLOCK"
#define WRX_MENU_VALUE_LEFT             "LEFT"
#define WRX_MENU_VALUE_RIGHT            "RIGHT"
#define WRX_MENU_VALUE_ROGER            "ROGER"
#endif

#ifdef ENABLE_JAPANESE
#define WRX_ACTION_TEXT(ja, ascii)       {ja, ascii}
#else
#define WRX_ACTION_TEXT(ja, ascii)       {ascii, NULL}
#endif

#define WRX_ACTION_NONE                  WRX_ACTION_TEXT(WRX_JA_ACTION_NONE, "NONE")
#define WRX_ACTION_FLASHLIGHT            WRX_ACTION_TEXT(WRX_JA_ACTION_FLASHLIGHT, "FLASH\nLIGHT")
#define WRX_ACTION_POWER                 WRX_ACTION_TEXT(WRX_JA_ACTION_POWER, "POWER")
#define WRX_ACTION_MONITOR               WRX_ACTION_TEXT(WRX_JA_ACTION_MONITOR, "MONITOR")
#define WRX_ACTION_SCAN                  WRX_ACTION_TEXT(WRX_JA_ACTION_SCAN, "SCAN")
#define WRX_ACTION_VOX                   WRX_ACTION_TEXT(WRX_JA_ACTION_VOX, "VOX")
#define WRX_ACTION_ALARM                 WRX_ACTION_TEXT(WRX_JA_ACTION_ALARM, "ALARM")
#define WRX_ACTION_FM                    WRX_ACTION_TEXT(WRX_JA_ACTION_FM, "FM")
#define WRX_ACTION_1750                  WRX_ACTION_TEXT(WRX_JA_ACTION_1750, "1750Hz")
#define WRX_ACTION_LOCK_KEYPAD           WRX_ACTION_TEXT(WRX_JA_ACTION_LOCK_KEYPAD, "LOCK\nKEYPAD")
#define WRX_ACTION_VFO_A_B               WRX_ACTION_TEXT(WRX_JA_ACTION_VFO_A_B, "VFO A\nVFO B")
#define WRX_ACTION_VFO_MEM              WRX_ACTION_TEXT(WRX_JA_ACTION_VFO_MEM, "VFO\nMEM")
#define WRX_ACTION_MODE                  WRX_ACTION_TEXT(WRX_JA_ACTION_MODE, "MODE")
#define WRX_ACTION_BLMIN_TMP_OFF         WRX_ACTION_TEXT(WRX_JA_ACTION_BLMIN_TMP_OFF, "BLMIN\nTMP OFF")
#define WRX_ACTION_RX_MODE               WRX_ACTION_TEXT(WRX_JA_ACTION_RX_MODE, "RX MODE")
#define WRX_ACTION_MAIN_ONLY             WRX_ACTION_TEXT(WRX_JA_ACTION_MAIN_ONLY, "MAIN ONLY")
#define WRX_ACTION_PTT                   WRX_ACTION_TEXT(WRX_JA_ACTION_PTT, "PTT")
#define WRX_ACTION_WIDE_NARROW           WRX_ACTION_TEXT(WRX_JA_ACTION_WIDE_NARROW, "W/N")
#define WRX_ACTION_MUTE                  WRX_ACTION_TEXT(WRX_JA_ACTION_MUTE, "MUTE")
#define WRX_ACTION_RXA                   WRX_ACTION_TEXT(WRX_JA_ACTION_RXA, "RxA")
#define WRX_ACTION_POWER_HIGH            WRX_ACTION_TEXT(WRX_JA_ACTION_POWER_HIGH, "POWER\nHIGH")
#define WRX_ACTION_REMOVE_OFFSET         WRX_ACTION_TEXT(WRX_JA_ACTION_REMOVE_OFFSET, "REMOVE\nOFFSET")
#define WRX_ACTION_BEAM                  WRX_ACTION_TEXT(WRX_JA_ACTION_BEAM, "BEAM")
#define WRX_ACTION_RF_LOG                WRX_ACTION_TEXT(WRX_JA_ACTION_RF_LOG, "RF LOG")
#define WRX_ACTION_FOXHUNT               WRX_ACTION_TEXT(WRX_JA_ACTION_FOXHUNT, "FOX HUNT\nBEACON")

#ifdef ENABLE_JAPANESE
#define WRX_MENU_CATEGORY_CHANNELS      WRX_JA_MENU_CATEGORY_CHANNELS
#define WRX_MENU_CATEGORY_SCAN          WRX_JA_MENU_CATEGORY_SCAN
#define WRX_MENU_CATEGORY_KEYS          WRX_JA_MENU_CATEGORY_KEYS
#define WRX_MENU_CATEGORY_POWER         WRX_JA_MENU_CATEGORY_POWER
#define WRX_MENU_CATEGORY_DISPLAY       WRX_JA_MENU_CATEGORY_DISPLAY
#define WRX_MENU_CATEGORY_TIMERS        WRX_JA_MENU_CATEGORY_TIMERS
#define WRX_MENU_CATEGORY_AUDIO         WRX_JA_MENU_CATEGORY_AUDIO
#define WRX_MENU_CATEGORY_RADIO         WRX_JA_MENU_CATEGORY_RADIO
#define WRX_MENU_CATEGORY_DTMF          WRX_JA_MENU_CATEGORY_DTMF
#define WRX_MENU_CATEGORY_SERVICE       WRX_JA_MENU_CATEGORY_SERVICE
#define WRX_MENU_CATEGORY_ALL           WRX_JA_MENU_CATEGORY_ALL
#else
#define WRX_MENU_CATEGORY_CHANNELS      "CHANNELS"
#define WRX_MENU_CATEGORY_SCAN          "SCAN"
#define WRX_MENU_CATEGORY_KEYS          "KEYS"
#define WRX_MENU_CATEGORY_POWER         "POWER"
#define WRX_MENU_CATEGORY_DISPLAY       "DISPLAY"
#define WRX_MENU_CATEGORY_TIMERS        "TIMERS"
#define WRX_MENU_CATEGORY_AUDIO         "AUDIO"
#define WRX_MENU_CATEGORY_RADIO         "RADIO"
#define WRX_MENU_CATEGORY_DTMF          "DTMF"
#define WRX_MENU_CATEGORY_SERVICE       "SERVICE"
#define WRX_MENU_CATEGORY_ALL           "ALL"
#endif

#endif
