#!/usr/bin/env python3
"""Generate the fixed external Japanese bitmap-font image for K1/K5 V3.

The input is Izumi 16's JIS X 0213 Plane 1 BDF.  Only JIS rows 1--47
(non-kanji plus JIS X 0208 first-level kanji) are selected.  ASCII remains
the firmware's existing compatibility font and is therefore not duplicated
in this external image.

The binary format is deliberately fixed and small:

    [sorted Unicode index: uint16 codepoint, uint16 glyph index]
    [glyphs: 16 rows x uint16, little-endian per row]

The firmware and host tool use the generated layout header/manifest.  There
is no runtime font negotiation or variable-width record format.
"""

from __future__ import annotations

import argparse
import gzip
import json
import struct
from pathlib import Path


FONT_BASE = 0x020000
NAME_BASE = 0x040000
NAME_RECORD_SIZE = 32
NAME_PAYLOAD_MAX = NAME_RECORD_SIZE - 1
SOURCE_SHA256 = "005345196615E692C54EF67286B44DD0EAA3A899D066CD407A4B3A810822C20"
SOURCE_URL = "https://unifoundry.com/japanese/izmg16-2004-1.bdf.gz"


def open_bdf(path: Path):
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="ascii")
    return path.open("r", encoding="ascii")


def jis_codepoint(character: str) -> int:
    encoded = character.encode("iso2022_jp")
    if not (encoded.startswith(b"\x1b$B") and encoded.endswith(b"\x1b(B")):
        raise ValueError(f"not a single JIS X 0208 character: {character!r}")
    return int.from_bytes(encoded[3:-3], "big")


def target_characters() -> list[str]:
    """Return JIS rows 0x21..0x4f in stable JIS order, without duplicates."""

    result: list[str] = []
    seen: set[str] = set()
    for row in range(0x21, 0x50):
        for cell in range(0x21, 0x7F):
            try:
                character = bytes((row + 0x80, cell + 0x80)).decode("euc_jp")
            except UnicodeDecodeError:
                continue
            if len(character) != 1 or character in seen:
                continue
            seen.add(character)
            result.append(character)
    return result


def parse_bdf(path: Path, wanted_codes: set[int]) -> dict[int, list[int]]:
    """Read 16x16 glyph rows keyed by JIS row-cell encoding."""

    lines = open_bdf(path).read().splitlines()
    glyphs: dict[int, list[int]] = {}
    index = 0
    while index < len(lines):
        if not lines[index].startswith("STARTCHAR "):
            index += 1
            continue

        end = index + 1
        while end < len(lines) and lines[end] != "ENDCHAR":
            end += 1
        block = lines[index:end]
        encoding_line = next((line for line in block if line.startswith("ENCODING ")), None)
        if encoding_line is None:
            index = end + 1
            continue
        code = int(encoding_line.split()[1])
        if code not in wanted_codes:
            index = end + 1
            continue

        bbx_line = next((line for line in block if line.startswith("BBX ")), None)
        bitmap_index = next((i for i, line in enumerate(block) if line == "BITMAP"), None)
        if bbx_line is None or bitmap_index is None:
            raise ValueError(f"missing BBX/BITMAP for JIS code 0x{code:04X}")
        bbx = [int(value) for value in bbx_line.split()[1:]]
        rows = block[bitmap_index + 1 : bitmap_index + 17]
        if bbx[:2] != [16, 16] or len(rows) != 16 or any(len(row) != 4 for row in rows):
            raise ValueError(f"JIS code 0x{code:04X} is not a 16x16 glyph")
        glyphs[code] = [int(row, 16) for row in rows]
        index = end + 1
    return glyphs


def write_layout_header(path: Path, glyph_count: int) -> None:
    index_bytes = glyph_count * 4
    bitmap_bytes = glyph_count * 32
    total_bytes = index_bytes + bitmap_bytes
    text = f"""/* Generated by tools/generate_japanese_font.py. */
#ifndef APP_JAPANESE_FONT_EXTERNAL_H
#define APP_JAPANESE_FONT_EXTERNAL_H

#define JAPANESE_FONT_FLASH_BASE       0x{FONT_BASE:06X}u
#define JAPANESE_FONT_INDEX_OFFSET     0u
#define JAPANESE_FONT_BITMAP_OFFSET    0x{index_bytes:06X}u
#define JAPANESE_FONT_GLYPH_COUNT      {glyph_count}u
#define JAPANESE_FONT_GLYPH_BYTES      32u
#define JAPANESE_FONT_INDEX_BYTES      {index_bytes}u
#define JAPANESE_FONT_BITMAP_BYTES     {bitmap_bytes}u
#define JAPANESE_FONT_TOTAL_BYTES      {total_bytes}u

#define JAPANESE_NAME_TABLE_BASE       0x{NAME_BASE:06X}u
#define JAPANESE_NAME_RECORD_SIZE      {NAME_RECORD_SIZE}u
#define JAPANESE_NAME_PAYLOAD_MAX      {NAME_PAYLOAD_MAX}u
#define JAPANESE_NAME_TABLE_SIZE       (1024u * JAPANESE_NAME_RECORD_SIZE)

#endif /* APP_JAPANESE_FONT_EXTERNAL_H */
"""
    path.write_text(text, encoding="utf-8", newline="\n")


def generate(args: argparse.Namespace) -> None:
    characters = target_characters()
    code_by_character = {character: jis_codepoint(character) for character in characters}
    wanted_codes = set(code_by_character.values())
    glyphs = parse_bdf(args.bdf, wanted_codes)
    missing = [character for character in characters if code_by_character[character] not in glyphs]
    if missing:
        preview = " ".join(f"U+{ord(character):04X}" for character in missing[:20])
        raise ValueError(f"missing {len(missing)} target glyphs: {preview}")

    entries = sorted((ord(character), code_by_character[character]) for character in characters)
    # Keep glyph order stable in JIS order while the index is Unicode-sorted.
    glyph_index = {code: index for index, (_character, code) in enumerate(
        (character, code_by_character[character]) for character in characters
    )}

    index_bytes = bytearray()
    bitmap_bytes = bytearray()
    for unicode_codepoint, jis_code in entries:
        index_bytes.extend(struct.pack("<HH", unicode_codepoint, glyph_index[jis_code]))
    for character in characters:
        for row in glyphs[code_by_character[character]]:
            bitmap_bytes.extend(struct.pack("<H", row))

    args.out_bin.parent.mkdir(parents=True, exist_ok=True)
    args.out_bin.write_bytes(index_bytes + bitmap_bytes)
    args.out_header.parent.mkdir(parents=True, exist_ok=True)
    write_layout_header(args.out_header, len(characters))

    manifest = {
        "format": "wrx-jp-external-font-v1",
        "source": {
            "name": "Izumi Gothic-Medium 16dot",
            "url": SOURCE_URL,
            "sha256": SOURCE_SHA256,
            "license": "Public Domain (as stated in the source BDF)",
        },
        "geometry": {"width": 16, "height": 16, "row_bytes": 2},
        "glyph_count": len(characters),
        "index_bytes": len(index_bytes),
        "bitmap_bytes": len(bitmap_bytes),
        "total_bytes": len(index_bytes) + len(bitmap_bytes),
        "flash_base": FONT_BASE,
        "name_table_base": NAME_BASE,
        "name_record_size": NAME_RECORD_SIZE,
        "name_payload_max": NAME_PAYLOAD_MAX,
        "ascii_fallback": "firmware-legacy-gFontBig",
        "codepoints": [unicode_codepoint for unicode_codepoint, _ in entries],
    }
    args.out_manifest.parent.mkdir(parents=True, exist_ok=True)
    args.out_manifest.write_text(
        json.dumps(manifest, ensure_ascii=True, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"glyphs: {len(characters)}")
    print(f"index: {len(index_bytes)} bytes")
    print(f"bitmap: {len(bitmap_bytes)} bytes")
    print(f"total: {len(index_bytes) + len(bitmap_bytes)} bytes")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("bdf", type=Path)
    parser.add_argument("--out-bin", type=Path, default=Path("docs/fonts/japanese_font.bin"))
    parser.add_argument("--out-header", type=Path, default=Path("App/japanese_font_external.h"))
    parser.add_argument("--out-manifest", type=Path, default=Path("tools/japanese_font_manifest.json"))
    generate(parser.parse_args())


if __name__ == "__main__":
    main()
